### ISSUE TITLE
style(input): missing bg-color on field

### ISSUE THREAD

**Issue by mxkaske** [openstatusHQ/openstatus#1035]
### How to reproduce

1. select dark mode
2. go to `/pricing`
3. scroll to the bottom of the page

### Currently

![CleanShot 2024-10-05 at 17 44 38@2x](https://github.com/user-attachments/assets/e6094f2f-a5b8-4a04-aff2-d59923fe0193)

### Should be

![CleanShot 2024-10-05 at 17 47 59@2x](https://github.com/user-attachments/assets/15a8592a-b1df-4439-a073-20a3b7badbcf)

### Solution

Missing `bg-background` color on the input.

**Comment by surajTade** [comment]
I would like to take this up....

**Comment by mxkaske** [comment]
Thanks @surajTade! Feel free to drop a PR.
