### ISSUE TITLE
Sticky date is not respecting sticky top navigation

### ISSUE THREAD

**Issue by mxkaske** [openstatusHQ/openstatus#1050]
### Description

We made the top navigation sticky and missed to update the `top-` position of the dates used within the blog / changelog page.

The value should stick below the header with a little padding to the border.

![CleanShot 2024-10-20 at 21 54 48@2x](https://github.com/user-attachments/assets/933ad15c-c5eb-459c-99d9-256dc9295565)

**Comment by Aejkatappaja** [comment]
#1055
