### ISSUE TITLE
[OPE-57] Save name and email in user table when a user sign up

### ISSUE THREAD

**Issue by thibaultleouay** [openstatusHQ/openstatus#107]
We should save name and user in the user table to avoid extra calls to clerk 

<sub>From [SyncLinear.com](https://synclinear.com) | [OPE-57](https://linear.app/openstatus/issue/OPE-57/save-name-and-email-in-user-table-when-a-user-sign-up)</sub>

**Comment by mxkaske** [comment]
Merged in #167
