### ISSUE TITLE
my monitor page doesn't show anything

### ISSUE THREAD

**Issue by Mahmoudgalalz** [openstatusHQ/openstatus#109]
my status page is empty and I have made a monitor to ping my site
and also there's no data recorded !!

![image](https://github.com/openstatusHQ/openstatus/assets/42272376/d3a6915e-1ade-45b5-a255-6dc1067a8ebf)

I have been added it 8h ago

**Comment by Mizerness** [comment]
Same issue

**Comment by GorlikItsMe** [comment]
Same issue (dont work since yesterday)

**Comment by thibaultleouay** [comment]
I'm on it ! 
From the data we fetch only the first 20 monitors,

**Comment by thibaultleouay** [comment]
Found the root cause the Vercel Edge Function was timeout after 25 sec, I'm pushing a fix for this 
it's in apps/web/src/app/api/check/cron

**Comment by thibaultleouay** [comment]
Just merged https://github.com/openstatusHQ/openstatus/pull/110 

What happened we where adding the jobs in a edge function we didnt stream response within the 25s and vercel cut the connection, it didn't add the other monitors to the 

I have removed the edge function we are a longer timeout, I have also removed the await within the loop 🤦

**Comment by thibaultleouay** [comment]
Just checked and the fix was good !
