### ISSUE TITLE
When I click the redirect link is relative so it misses the way

### ISSUE THREAD

**Issue by Mahmoudgalalz** [openstatusHQ/openstatus#113]
![image](https://github.com/openstatusHQ/openstatus/assets/42272376/8d613632-a4f7-4338-8025-4dbed2b32e43)

when I click here it directs me to the path but relative with the subdomain,

there are two solutions to that
- putting the full URI
- redirect on subdomain level

**Comment by thibaultleouay** [comment]
I have just checked and this is fixed
