### ISSUE TITLE
provide a way to un track these IP from analytics

### ISSUE THREAD

**Issue by Mahmoudgalalz** [openstatusHQ/openstatus#114]
this way we lead to too much miss good analytics, as edge will use different ips each time even for the same region

so is there's a way to prevent that ?!

**Comment by thibaultleouay** [comment]
@Mahmoudgalalz  We dont execute any js when fetching the data thus it should not trigger most of the analytics service 

Otherwise something we could do is to add an user Agent to the request to easily remove them from analytics

**Comment by Mahmoudgalalz** [comment]
The service I use it embed the js within the html file
So, the user agent option is really usefull

Thanks @thibaultleouay

**Comment by mxkaske** [comment]
Thanks for asking @Mahmoudgalalz. 

Yep, we could also think of adding an additional request header property `"openstatus-no-track"`.

Seen in Steven's [middleware](https://github.com/steven-tey/dub/blob/04c5401fcd993c64134ddfc91df775af7b578d12/lib/middleware/link.ts#L32).

**Comment by Mahmoudgalalz** [comment]
I can work on it if it possible

**Comment by thibaultleouay** [comment]
@Mahmoudgalalz feel free to provide a PR 🙏

**Comment by mxkaske** [comment]
Hey @Mahmoudgalalz, may I ask if you have worked on it? Otherwise, this one could be a **good first issue** to provide!

**Comment by Mahmoudgalalz** [comment]
I will send a PR tmrw🚀🎉
