### ISSUE TITLE
500 error code randomly 

### ISSUE THREAD

**Issue by shawshankkumar** [openstatusHQ/openstatus#117]
Once in a while when I open farmako.openstatus.dev it throws a 500 error and then on refresh it starts working. It doesn't happen all the time. I wonder what it is, probably something related db?

**Comment by thibaultleouay** [comment]
Thanks for opening this, 
I will monitor it and dig our log later today

**Comment by shawshankkumar** [comment]
Please let me know if i can help

**Comment by mxkaske** [comment]
Hey @shawshankkumar, can you recheck if the issue still occurs. When trying it out from time to time, the subdomain slug `farmako` worked fine for me.

**Comment by shawshankkumar** [comment]
Hey,
We haven't faced this issues again in the last few days. I'll keep you
posted if it happens again
thanks!

**Comment by mxkaske** [comment]
Thanks @shawshankkumar for the response. Please reopen an issue if you re-encounter it.
