### ISSUE TITLE
Invalid environment variables: { DATABASE_URL: [ 'Required' ] }

### ISSUE THREAD

**Issue by Adamkaram** [openstatusHQ/openstatus#12]
i'm trying to play with this project but i got this error 

web:dev: - ready started server on 0.0.0.0:3000, url: http://localhost:3000
web:dev: ❌ Invalid environment variables: { DATABASE_URL: [ 'Required' ] }
web:dev: Error: Invalid environment variables
web:dev:     at c (file:///C:/Users/Adam/openstatus-main/node_modules/.pnpm/@t3-oss+env-core@0.4.1_typescript@5.1.3_zod@3.21.4/node_modules/@t3-oss/env-core/dist/index.mjs:1:426)

i know it's related to env var but wich one i cant find tree of  it or where's came from 

aslo is there's any env file except this ?
![Screenshot 2023-06-29 224936](https://github.com/mxkaske/openstatus/assets/52092726/6e7f867d-4e0c-4c74-af6a-e9ae4c9374f8)

**Comment by mxkaske** [comment]
We are using the `DATABASE_URL` from planetscale. It's missing in the `.env.example` files.

**Comment by Adamkaram** [comment]
> planetscale

i used railway postgress and it works just as fine

**Comment by thibaultleouay** [comment]
@Adamkaram  
When we release the monitoring/status system, we will use Planetscale as the database.
The UI components will work, but the migration won't. We use Drizzle ORM.

**Comment by Adamkaram** [comment]
> @Adamkaram When we release the monitoring/status system, we will use Planetscale as the database. The UI components will work, but the migration won't. We use Drizzle ORM.

so i will move back to planetscale

**Comment by Ipriyankrajai** [comment]
Hello guys,
I would like to contribute. What is the road-map?

**Comment by mxkaske** [comment]
Thanks @Ipriyankrajai ! We do not yet have any public roadmap or ways to contribute yet. We will think about 'how to' with @thibaultleouay.

**Comment by Ipriyankrajai** [comment]
Hey @mxkaske ,
I'm excited to work together on the project! Anticipating great results. Looking forward to collaborating closely, contributing my skills, and learning from you. Making a meaningful impact. Let's create something exceptional! Thank you for this opportunity.

**Comment by mxkaske** [comment]
Sorry for the long waiting. We published some of our roadmap via linear tickets thanks to synclinear. Most of the tasks can be started after the “alpha” release (once the platform achieved some stability). Right now, we are in a phase where we potentially break stuff on purpose. If there is already something you want to work on, that can be encapsulated, feel free to let us know!

The easiest way of communication is direct. Here is the [cal.com](https://cal.com/thibault-openstatus/30min) link!

We hope you understand it!
