### ISSUE TITLE
Monitor Data Page dont display any data

### ISSUE THREAD

**Issue by thibaultleouay** [openstatusHQ/openstatus#121]
The monitor datapage is blank

**Comment by Mahmoudgalalz** [comment]
and still we don't get the data on the status page #109

**Comment by thibaultleouay** [comment]
@Mahmoudgalalz I have been trying to monitor your site but your site seems to be down, 
We have a too many redirect error while trying to get data, 

We should add some error in the database, 
I will work on it after work day !

**Comment by Mahmoudgalalz** [comment]
@thibaultleouay yeah, I know there's many redirecting

It should show me that

And i have tried google to test, it also doesn't get anything back

**Comment by thibaultleouay** [comment]
@Mahmoudgalalz I have a fix coming 🔥

**Comment by thibaultleouay** [comment]
@Mahmoudgalalz  for your google monitor it should work I see some data

 we might have some cache issue with NextJs but we are trying to figure it out !  if you reload the page it should work 
 
 You can send me an email thibault@openstatus.dev and I will share the data I have for your google monitor

**Comment by thibaultleouay** [comment]
This is fixed 

In our tinybird query we were fetching everything even the metadata that contains the content of the page 

@mxkaske  has fixed it 

![CleanShot 2023-08-01 at 20 44 00](https://github.com/openstatusHQ/openstatus/assets/13894054/36d11cdf-181a-4e03-8277-584adb3a00e0)
