### ISSUE TITLE
Date handling on monitor and status page

### ISSUE THREAD

**Issue by ramonmetzker** [openstatusHQ/openstatus#123]
First of all, the requests are working super well, awesome!

I've noticed most of the bugs like "data not showing" and related are due to how date is being handled.
When we access the monitor page it should pick the data from the current day, right now it is fetching from the previous day; if we set the date to today, it is possible to verify it. It also happens on the status page, only there we can't set the date to validate this issue.

**Comment by thibaultleouay** [comment]
@ramonmetzker  Thanks for showing your interest on the project !  
We also have some cache issue sometimes if you refresh the page the data is ok, 
I need to see how to refresh cache !

**Comment by mxkaske** [comment]
Hey @ramonmetzker, we had some issues regarding the payload size of tinybird (exceeding 100MB because we are storing the `res.text()`). Also we did some caching improvements.

Let us know if it still occurs!

**Comment by mxkaske** [comment]
I'll close the issue. We improved tinybird as described in #278 to reduced the data processed. Feel free to reopen the issue if it re-occurs.
