### ISSUE TITLE
[OPE-59] Improve email

### ISSUE THREAD

**Issue by thibaultleouay** [openstatusHQ/openstatus#135]
![Screenshot_20230802-100256.png](https://uploads.linear.app/f4459157-1807-4ecb-81eb-4d236f5fc5d1/99d62a52-7978-46e3-aa1e-98cfd7ddfdb0/e0eaa057-b8c8-4eab-9757-925cf727ccdb?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y0NDU5MTU3LTE4MDctNGVjYi04MWViLTRkMjM2ZjVmYzVkMS85OWQ2MmE1Mi03OTc4LTQ2ZTMtYWExZS05OGNmZDdkZGZkYjAvZTBlYWEwNTctYjhjOC00ZWFiLTk3NTctOTI1Y2Y3MjdjY2RiIiwiaWF0IjoxNjkwOTkzMjc5LCJleHAiOjE2OTEwNzk2Nzl9.f-v_RX1vjq-vq9Ulmys5Dg1m4NzgHqVh_GO2BS7klJw)

we should see some content bellow the title 

<sub>From [SyncLinear.com](https://synclinear.com) | [OPE-59](https://linear.app/openstatus/issue/OPE-59/improve-email)</sub>

**Comment by AmoabaKelvin** [comment]
Hey @thibaultleouay , the screenshot preview does not show and when you try visiting it, you get an invalid upstream response(401)
<img width="279" alt="image" src="https://github.com/openstatusHQ/openstatus/assets/97001695/60f1dc13-871d-4b76-a53d-e0c38589d074">
