### ISSUE TITLE
[OPE-61] On monitor creation form we should block if the user has not selected a frequency

### ISSUE THREAD

**Issue by thibaultleouay** [openstatusHQ/openstatus#140]
Some users did not select a frequency and they were able to create a monitor,  it could lead to a bad ux 

<sub>From [SyncLinear.com](https://synclinear.com) | [OPE-61](https://linear.app/openstatus/issue/OPE-61/on-monitor-creation-form-we-should-block-if-the-user-has-not-selected)</sub>

**Comment by mxkaske** [comment]
So let's make it `required`. We can also add a default value of `10m` e.g.

**Comment by webAbhi** [comment]
Can i open a PR for this ?

**Comment by mxkaske** [comment]
Hey @webAbhi, thanks for your interest. I’ll close this issue because it has been fixed in #159. Our bad!
