### ISSUE TITLE
Invalid environment variables JITSU_HOST, JITSU_WRITE_KEY

### ISSUE THREAD

**Issue by johanruizb** [openstatusHQ/openstatus#143]
### Error Description:

When running the steps of the repository and using `pnpm dev`, I encounter the following error when trying to access `localhost:3000`:

```bash
web:dev: ❌ Invalid environment variables: { JITSU_HOST: [ 'Required' ], JITSU_WRITE_KEY: [ 'Required' ] }
web:dev: - wait compiling /_error (client and server)...
web:dev: - error ../node_modules/.pnpm/@t3-oss+env-core@0.6.0_typescript@5.1.6_zod@3.21.4/node_modules/@t3-oss/env-core/dist/index.mjs (1:501) @ y
web:dev: - error Error: Invalid environment variables
web:dev:     at y (webpack-internal:///(rsc)/../../node_modules/.pnpm/@t3-oss+env-core@0.6.0_typescript@5.1.6_zod@3.21.4/node_modules/@t3-oss/env-core/dist/index.mjs:11:91)
web:dev:     at h (webpack-internal:///(rsc)/../../node_modules/.pnpm/@t3-oss+env-core@0.6.0_typescript@5.1.6_zod@3.21.4/node_modules/@t3-oss/env-core/dist/index.mjs:15:31)
web:dev:     at eval (webpack-internal:///(rsc)/../../packages/analytics/env.ts:9:72)
web:dev:     at (rsc)/../../packages/analytics/env.ts (/home/user/Documentos/openstatus/apps/web/.next/server/app/page.js:5960:1)
web:dev:     at __webpack_require__ (/home/user/Documentos/openstatus/apps/web/.next/server/webpack-runtime.js:33:42)
web:dev:     at eval (webpack-internal:///(rsc)/./src/env.ts:8:83)
web:dev:     at (rsc)/./src/env.ts (/home/user/Documentos/openstatus/apps/web/.next/server/app/page.js:3774:1)
web:dev:     at __webpack_require__ (/home/user/Documentos/openstatus/apps/web/.next/server/webpack-runtime.js:33:42)
web:dev:     at eval (webpack-internal:///(rsc)/./src/lib/tb.ts:7:62)
web:dev:     at (rsc)/./src/lib/tb.ts (/home/user/Documentos/openstatus/apps/web/.next/server/app/page.js:3785:1) {
web:dev:   digest: undefined
web:dev: }
web:dev: null
```

### Error Explanation:

The error message indicates that there are invalid environment variables, specifically `JITSU_HOST` and `JITSU_WRITE_KEY`. The error seems to be occurring in the file `env-core/dist/index.mjs` from the `@t3-oss/env-core` package version 0.6.0 with TypeScript version 5.1.6 and Zod version 3.21.4. The specific line where the error is triggered is line 1, column 501 (1:501).

The error traceback suggests that the issue is related to the file `analytics/env.ts` at line 9, column 72, and the file `src/env.ts` at line 8, column 83. Additionally, there is a reference to `src/lib/tb.ts` at line 7, column 62.

analytics/env.ts content:
```typescript
import { createEnv } from "@t3-oss/env-core";
import { z } from "zod";

export const env = createEnv({
  server: {
    JITSU_HOST: z.string(),
    JITSU_WRITE_KEY: z.string(),
  },
  runtimeEnv: {
    JITSU_HOST: process.env.JITSU_HOST,
    JITSU_WRITE_KEY: process.env.JITSU_WRITE_KEY,
  },
});
```

### Steps Taken:

1. Checked the `.env` file to ensure that `JITSU_HOST` and `JITSU_WRITE_KEY` are properly defined, but they seem to be correctly set.
2. Verified the `env.ts` file and ensured that the variables are being imported and accessed correctly.

### Expected Behavior:

When executing `pnpm dev` and accessing `localhost:3000`, the application should run without any errors related to invalid environment variables.

### Additional Information:

**Operating System:** Ubuntu 22.04.2 LTS (Jammy Jellyfish)

**Node.js Version:** 18.16.0

**pnpm Version:** 8.6.10

**Comment by mxkaske** [comment]
Both `JITSU_` environment variables have to also be added inside of the `apps/web/.env` file.

Sorry about the inconvenience. We will update the `.env.example`.
