### ISSUE TITLE
Z-index stacking issue on Safari

### ISSUE THREAD

**Issue by PieterDePauw** [openstatusHQ/openstatus#145]
There seems to be an issue with the z-index of the HoverCard on the landing page in Safari. The card is displayed behind the content below, if the card is rendered underneath.

<img width="1081" alt="Screenshot 2023-08-03 at 00 23 22" src="https://github.com/openstatusHQ/openstatus/assets/44448043/b2a67c94-5b74-4dfa-bbc2-7840e2057e65">

The issue seems to discussed on the following page: [https://ecomgraduates.com/blogs/news/fixing-z-index-issue-on-safari-browser](https://ecomgraduates.com/blogs/news/fixing-z-index-issue-on-safari-browser)

**Comment by mxkaske** [comment]
Thanks for sharing, @PieterDePauw! Something we have not noticed because as default, the hover card position is 'top'.
