### ISSUE TITLE
Public project Support

### ISSUE THREAD

**Issue by ramazansancar** [openstatusHQ/openstatus#18]
How do you look at converting it to a public project with subdomain or path?

See example: https://github.com/fatih-yavuz/my-links

The sustainability of the project can also be ensured by adding certain limits that anyone can use by signing up with a dashboard.

**Comment by Ipriyankrajai** [comment]
I think most efficient way is using subdomain

**Comment by thibaultleouay** [comment]
Hello @ramazansancar  
What do you mean by converting it to a public project? 

We are working on a roadmap with @mxkaske hope this will help.

**Comment by ramazansancar** [comment]
> Hello @ramazansancar What do you mean by converting it to a public project?
> 
> We are working on a roadmap with @mxkaske hope this will help.

It can be organized as a status page that can be turned into a product and controlled via github or dashboard.

**Comment by mxkaske** [comment]
> > Hello @ramazansancar What do you mean by converting it to a public project?
> > We are working on a roadmap with @mxkaske hope this will help.
> 
> It can be organized as a status page that can be turned into a product and controlled via github or dashboard.

Still not getting it 😅.

Thanks guys! ❤️ Appreciate the commitment. As @thibaultleouay said, we will take a closer look. Might take a few days but we will be back soon with some details. 🙏

**Comment by mxkaske** [comment]
Read more here: https://github.com/openstatusHQ/openstatus/issues/12#issuecomment-1633093915
