### ISSUE TITLE
[OPE-63] Add drag and drop to monitors to change order for status page

### ISSUE THREAD

**Issue by mxkaske** [openstatusHQ/openstatus#189]
The order is currently fixed by the dabase query. It would be great to allow the user to change it as (s)he likes to!

<sub>From [SyncLinear.com](https://synclinear.com) | [OPE-63](https://linear.app/openstatus/issue/OPE-63/add-drag-and-drop-to-monitors-to-change-order-for-status-page)</sub>

**Comment by PeterKwesiAnsah** [comment]
@mxkaske I would like to take this on.
Any Screenshots or additional Information Available ??

**Comment by mxkaske** [comment]
Hey @PeterKwesiAnsah! No screenshot available. But it would be great to make it work with tanstack/table. If you have a first suggestion, feel free to comment it.
