### ISSUE TITLE
[OPE-77] Provide a way to untrack ping requests (e.g. from analytics)

### ISSUE THREAD

**Issue by mxkaske** [openstatusHQ/openstatus#190]
We could think of adding an additional request header property `"openstatus-no-track"` or a custom user agent.

Seen in Steven's [middleware](https://github.com/steven-tey/dub/blob/04c5401fcd993c64134ddfc91df775af7b578d12/lib/middleware/link.ts#L32).

Feature Request #114

<sub>From [SyncLinear.com](https://synclinear.com) | [OPE-77](https://linear.app/openstatus/issue/OPE-77/provide-a-way-to-untrack-ping-requests-eg-from-analytics)</sub>

**Comment by Mahmoudgalalz** [comment]
I would like to ask, we would like to add a header within the hit request
that has "openstatus-no-track", which user will check if this header is exist, it should ignore tracking right

so simplly what I'm going to do is adding the header within the request, and also might add a user agent within the request

is that what I should only do right ?

**Comment by Mahmoudgalalz** [comment]
@mxkaske

**Comment by mxkaske** [comment]
Hey @Mahmoudgalalz! Correct. I would only add the requesr header and keep the user agent as for now to avoid manipulating it. 🔥

Now, writing about it, we should call the header differently. Instead of 'openstatus-no-track', which will always be set, we can have a

```
"OpenStatus-Ping": true
```

property inside the header as it affects all the requests we are doing. 👀

**Comment by Mahmoudgalalz** [comment]
why it has been reopened ? @mxkaske is there's a problem ?!
