### ISSUE TITLE
[OPE-78] Setup localhost and update documentation

### ISSUE THREAD

**Issue by mxkaske** [openstatusHQ/openstatus#191]
The goal is to setup localhost and make it running (ideally we'll have it for Mac/Linux and Windows). Let us know about the issues you encountered and update the docs.

Also, it appears that the metadata for the docs are **not** correct. It would be great to have them. For the OG image, you can use the link [https://openstatus.dev/api/og](https://www.openstatus.dev/api/og) and append `title` and `description` as search params.

The main services to setup are:

1. tinybird
2. clerk
3. turso
4. nextjs
5. qstash

If you have any issue, please contact us on [discord](https://discord.com/invite/dHD4JtSfsn)!

<sub>From [SyncLinear.com](https://synclinear.com) | [OPE-78](https://linear.app/openstatus/issue/OPE-78/setup-localhost-and-update-documentation)</sub>

**Comment by Dkingofcode** [comment]
Can i work on this issue, seems like an interesting challenge.

**Comment by mxkaske** [comment]
We have more and more docs about setting it up. Feel free to try it out and improve it!

**Comment by skushagra9** [comment]
This issue is solved ??
Website is up to date
Do you want changes in the github docs also ??
