### ISSUE TITLE
[OPE-36] Improve Monitor Data Table

### ISSUE THREAD

**Issue by mxkaske** [openstatusHQ/openstatus#194]
### Pagination

Right now, we only have client side pagination. It would be great to have server side pagination to be able to share pages at some point and only load needed data.

### Limits

Same for the limits.

Create page pagination (e.g. `/app/[workspace-slug]/monitors/[id]/data/1?limit=10`, `/app/[workspace-slug]/monitors/[id]/data/2?limit=10`) which then gets offset data from tinybird.

```
SELECT *
FROM your_table
ORDER BY some_column
LIMIT 10 OFFSET 20;
```

Resources:

* [Josh tried coding](https://www.youtube.com/watch?v=SXmni_7B0r4)
* …

<sub>From [SyncLinear.com](https://synclinear.com) | [OPE-36](https://linear.app/openstatus/issue/OPE-36/improve-monitor-data-table)</sub>

**Comment by Harish-b-03** [comment]
Hello @mxkaske :wave:,

Following our conversation on Discord, I'm interested in working on this issue. Could you kindly assign it to me?

Thank you!

**Comment by PeterKwesiAnsah** [comment]
@mxkaske Can you reassign this issue to me ??
I have started working on it
T for Thanks

**Comment by mxkaske** [comment]
I'd say just create a PR for it! 🚀

**Comment by mxkaske** [comment]
We will keep the client side pagination for now.
