### ISSUE TITLE
[OPE-79] Add author avatar and url to blog post page

### ISSUE THREAD

**Issue by mxkaske** [openstatusHQ/openstatus#196]
We include the `author.avatar` and `author.url` to the blog post documents. It would be great to include a rounded `Avatar` (using shadcn) and wrap the name around a `Link`.

<sub>From [SyncLinear.com](https://synclinear.com) | [OPE-79](https://linear.app/openstatus/issue/OPE-79/add-author-avatar-and-url-to-blog-post-page)</sub>

**Comment by AmoabaKelvin** [comment]
Let me pick this up @mxkaske. Where should the link point to?

**Comment by AmoabaKelvin** [comment]
Seen, every Author object has a url attached. Perhaps, point to that url right?

**Comment by mxkaske** [comment]
Hey @AmoabaKelvin, yep, exactly. Both attributes should be available for a post. The url should open a new tab. 🚀

There is no design, follow shadcn ui guidelines and you should be good to go. 😅

**Comment by AmoabaKelvin** [comment]
Hello @mxkaske I got on to work on this but I am encountering this error when I click on the blog post. So it shows up when I visit `http://localhost:3000/blog/the-first-48-hours`. I am figuring it out but leaving it here in case you had already encountered and solved it.

<img width="1232" alt="image" src="https://github.com/openstatusHQ/openstatus/assets/97001695/5709a91e-0bc4-4f8c-bc41-14627cdaae06">


here is the complete error message.
```
Unhandled Runtime Error
Error: Cannot read properties of undefined (reading 'screen_name')

Call Stack
screen_name
../node_modules/.pnpm/react-tweet@3.0.3_react-dom@18.2.0_react@18.2.0/node_modules/react-tweet/dist/utils.js (1:63)
getTweetUrl
../node_modules/.pnpm/react-tweet@3.0.3_react-dom@18.2.0_react@18.2.0/node_modules/react-tweet/dist/utils.js (132:13)
t
../node_modules/.pnpm/react-tweet@3.0.3_react-dom@18.2.0_react@18.2.0/node_modules/react-tweet/dist/twitter-theme/embedded-tweet.js (15:42)
nextCreate
../node_modules/.pnpm/next@13.4.12_@babel+core@7.22.9_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-server-dom-webpack-experimental/cjs/react-server-dom-webpack-server.edge.development.js (911:11)
useMemo
../node_modules/.pnpm/next@13.4.12_@babel+core@7.22.9_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-experimental/cjs/react.shared-subset.development.js (1789:20)
EmbeddedTweet
../node_modules/.pnpm/react-tweet@3.0.3_react-dom@18.2.0_react@18.2.0/node_modules/react-tweet/dist/twitter-theme/embedded-tweet.js (15:26)
type
../node_modules/.pnpm/next@13.4.12_@babel+core@7.22.9_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-server-dom-webpack-experimental/cjs/react-server-dom-webpack-server.edge.development.js (1610:17)
attemptResolveElement
../node_modules/.pnpm/next@13.4.12_@babel+core@7.22.9_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-server-dom-webpack-experimental/cjs/react-server-dom-webpack-server.edge.development.js (1957:20)
resolveModelToJSON
../node_modules/.pnpm/next@13.4.12_@babel+core@7.22.9_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-server-dom-webpack-experimental/cjs/react-server-dom-webpack-server.edge.development.js (1412:13)
stringify
<anonymous>
stringify
../node_modules/.pnpm/next@13.4.12_@babel+core@7.22.9_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-server-dom-webpack-experimental/cjs/react-server-dom-webpack-server.edge.development.js (2635:13)
processModelChunk
../node_modules/.pnpm/next@13.4.12_@babel+core@7.22.9_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-server-dom-webpack-experimental/cjs/react-server-dom-webpack-server.edge.development.js (2341:25)
retryTask
../node_modules/.pnpm/next@13.4.12_@babel+core@7.22.9_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-server-dom-webpack-experimental/cjs/react-server-dom-webpack-server.edge.development.js (2388:6)
performWork
../node_modules/.pnpm/next@13.4.12_@babel+core@7.22.9_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-server-dom-webpack-experimental/cjs/react-server-dom-webpack-server.edge.development.js (1707:13)
listOnTimeout
node:internal/timers (569:17)
process.processTimers
node:internal/timers (512:7)
```

**Comment by AmoabaKelvin** [comment]
I did a little digging in and it appears to be a problem with the package. This [issue](https://github.com/vercel/react-tweet/issues/129) in their repo talked about the same problem and the proposed fix was updating the version of the package from `v3.0.3` to `v3.1.1`.

After the update, it worked perfectly.

I think we might want to effect that change to prevent future contributors from running into the same problem. Let me know what you think.

**Comment by AmoabaKelvin** [comment]
Also @mxkaske , I worked on this, let me know what you think about it. Once it's okay, I will push and open a PR
<img width="769" alt="image" src="https://github.com/openstatusHQ/openstatus/assets/97001695/68a1111a-5da7-4040-8ebd-0a8b1aee1cb7">

**Comment by mxkaske** [comment]
Good work @AmoabaKelvin and thanks for the investigation. Looks great! 😍 I'd suggest you push the package version bump as well and create a PR. 🚀
