### ISSUE TITLE
[OPE-84] Replace filter status code input field with combox like 'region'

### ISSUE THREAD

**Issue by mxkaske** [openstatusHQ/openstatus#221]
There is no need for the status code input. We should replace it with the similar component/behavior like the region one.

The only difficulty is do create the select list dynamically, based on the content we get.

It can be that at some point, we have status `200`, `500`, `429` and another one where we have `200`, `500`, `404` - the select options should reflect accordingly.

![CleanShot 2023-09-24 at 18 41 00@2x](https://github.com/openstatusHQ/openstatus/assets/56969857/d6021c0b-6305-4a35-b162-250d240c510f)

<sub>From [SyncLinear.com](https://synclinear.com) | [OPE-84](https://linear.app/openstatus/issue/OPE-84/replace-filter-status-code-input-field-with-combox-like-region)</sub>

**Comment by adithyaakrishna** [comment]
Can I take this up?

**Comment by adithyaakrishna** [comment]
Can I take this up?

**Comment by mxkaske** [comment]
Please 🚀

**Comment by mxkaske** [comment]
Hey @adithyaakrishna, are you on it? Otherwise I'd reassign the issue.

**Comment by hrutik7** [comment]
hey @mxkaske if possible can you please assign this issue to me ?

**Comment by nicolasVenard** [comment]
Hey, I'd like to work on this too ? 🙂

**Comment by hrutik7** [comment]
hey @nicolasVenard work is in progress I am just not getting status from `getResponseList()` as soon as I figured this out i'll raised the PR

**Comment by hrutik7** [comment]
@nicolasVenard are you getting status from `getResponseList()`
