### ISSUE TITLE
bug: auto-generate slug

### ISSUE THREAD

**Issue by mxkaske** [openstatusHQ/openstatus#231]
With #198 we have introduced a bug and temporarily disabled the functionality for now.

The reason: If your slug was different to what would have been generated, whenever you would re-edit a page, it would `slugify` the title on every form opening.

How to reproduce:

1. uncomment the lines here:
https://github.com/openstatusHQ/openstatus/blob/7a80fbdd643174f20e2d90c3bc3d63422652b646/apps/web/src/components/forms/status-page-form.tsx#L95
2. create a status page (edited) with a `title` and change the `slug` that has been auto generated - and save
3. edit the same status page (edited) - the `slug` should have been updated to the auto generated one, not the one saved

**Comment by AmoabaKelvin** [comment]
I'm taking this up.

**Comment by AmoabaKelvin** [comment]
Did you mean create a status page with a custom slug or monitor?
Because there is no slug field in the monitor creation/edit form.

**Comment by mxkaske** [comment]
Oh boy, I meant the status-page 😅
