### ISSUE TITLE
[OPE-86] Only show `body` Input when advanced monitor settings method is "POST"

### ISSUE THREAD

**Issue by mxkaske** [openstatusHQ/openstatus#232]
The `body` textarea should be `hidden` if "GET" is chosen. Otherwise, if a user is selecting the "GET" method and adds a body, we will get:

```
[TypeError: Request with GET/HEAD method cannot have body.]
```

<sub>From [SyncLinear.com](https://synclinear.com) | [OPE-86](https://linear.app/openstatus/issue/OPE-86/only-show-body-input-when-advanced-monitor-settings-method-is-post)</sub>

**Comment by zahid47** [comment]
I would like to attempt this!

**Comment by AmoabaKelvin** [comment]
Sure. That will be great 🚀
