### ISSUE TITLE
Once the number of pages for the quota is up, it will be great to show a popover or something when the user hovers over the create card so they don't think its broken

### ISSUE THREAD

**Issue by AmoabaKelvin** [openstatusHQ/openstatus#245]
Though it's written at the bottom of the page, it will be great to show it on button hover as well. Let me know what you think.
<img width="135" alt="image" src="https://github.com/openstatusHQ/openstatus/assets/97001695/e9dbe623-cf4f-4db9-a47b-d9f7b0391d07">

**Comment by mxkaske** [comment]
~We have the little text that is written here. But~ I agree, that we can inform the user a bit more. How about a `Tooltip` with the same additional information?

<img width="229" alt="CleanShot 2023-08-27 at 13 36 52@2x" src="https://github.com/openstatusHQ/openstatus/assets/56969857/a686e46e-49c6-41b6-8614-8879525f87ee">

**Comment by AmoabaKelvin** [comment]
Yes. A Tooltip is what we'll need.

**Comment by zahid47** [comment]
We also need it for the monitors page

**Comment by mxkaske** [comment]
Very good call!

**Comment by zahid47** [comment]
looks like this is already fixed? #279

**Comment by AmoabaKelvin** [comment]
That's correct
