### ISSUE TITLE
[OPE-88] Add `active` information of monitor on incident creation

### ISSUE THREAD

**Issue by mxkaske** [openstatusHQ/openstatus#246]
Inform the user which monitors are active to give more context. Sometimes, you have inactive onces!

TODO: Similar to our Badges, we add a small rounded `span` with a background color. Could be done here behind the monitor title as well

![CleanShot 2023-08-27 at 13.24.16@2x.png](https://uploads.linear.app/f4459157-1807-4ecb-81eb-4d236f5fc5d1/ddf40e46-3d49-4739-9c6c-8b9d6747c434/15944050-5677-48d1-b500-41fd036cd223?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y0NDU5MTU3LTE4MDctNGVjYi04MWViLTRkMjM2ZjVmYzVkMS9kZGY0MGU0Ni0zZDQ5LTQ3MzktOWM2Yy04YjlkNjc0N2M0MzQvMTU5NDQwNTAtNTY3Ny00OGQxLWI1MDAtNDFmZDAzNmNkMjIzIiwiaWF0IjoxNjkzMTM1Njk5LCJleHAiOjE2OTMyMjIwOTl9.AfJT868lza9tQWiB0sAGDIs4nO17L9YGW5dYurENoH0)

<sub>From [SyncLinear.com](https://synclinear.com) | [OPE-88](https://linear.app/openstatus/issue/OPE-88/add-active-information-of-monitor)</sub>

**Comment by AmoabaKelvin** [comment]
Picking this up 🚀
