### ISSUE TITLE
[OPE-89] Add information about Method for the monitors overview

### ISSUE THREAD

**Issue by mxkaske** [openstatusHQ/openstatus#247]
Important for the user to know on first glance what the method of the monitor is as we have added "POST" methods to it as well.

![CleanShot 2023-08-27 at 13.32.15@2x.png](https://uploads.linear.app/f4459157-1807-4ecb-81eb-4d236f5fc5d1/a21320cc-44de-4a1c-9803-d5c700e5cfcc/6973d52a-2ec4-4f39-a33a-ca34a38b6eb5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y0NDU5MTU3LTE4MDctNGVjYi04MWViLTRkMjM2ZjVmYzVkMS9hMjEzMjBjYy00NGRlLTRhMWMtOTgwMy1kNWM3MDBlNWNmY2MvNjk3M2Q1MmEtMmVjNC00ZjM5LWEzM2EtY2EzNGEzOGI2ZWI1IiwiaWF0IjoxNjkzMTM2MDMyLCJleHAiOjE2OTMyMjI0MzJ9.PGnb0OCqYpKm3YOA0NkOR-jwbWLavadcYq0p8zr1vdU)

<sub>From [SyncLinear.com](https://synclinear.com) | [OPE-89](https://linear.app/openstatus/issue/OPE-89/add-information-about-method-for-the-monitors-overview)</sub>

**Comment by zahid47** [comment]
I would like to attempt this!

**Comment by zahid47** [comment]
I think a `Badge` would look good to show the method name and use different colored badges based on the method type

**Comment by mxkaske** [comment]
Go for it! 🚢
