### ISSUE TITLE
[OPE-90] The OG image bars are in the wrong order.

### ISSUE THREAD

**Issue by mxkaske** [openstatusHQ/openstatus#252]
The red bar should be on the right! - Needs to be inverted

Also, we have a separate OG implementation for the status bars. It should include the latest changes from the `<Tracker/>`!

![CleanShot 2023-08-27 at 19.14.09@2x.png](https://uploads.linear.app/f4459157-1807-4ecb-81eb-4d236f5fc5d1/c9c487d9-4b1e-4764-b1af-6670c623c498/14c32b2f-0dd5-451b-90f2-68a1735e03b6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y0NDU5MTU3LTE4MDctNGVjYi04MWViLTRkMjM2ZjVmYzVkMS9jOWM0ODdkOS00YjFlLTQ3NjQtYjFhZi02NjcwYzYyM2M0OTgvMTRjMzJiMmYtMGRkNS00NTFiLTkwZjItNjhhMTczNWUwM2I2IiwiaWF0IjoxNjkzMTU2NTEzLCJleHAiOjE2OTMyNDI5MTN9.oj557GLwWeII-IY6C5Ty8kM1G2GD4OJMiILpf2zIqiI)

<sub>From [SyncLinear.com](https://synclinear.com) | [OPE-90](https://linear.app/openstatus/issue/OPE-90/the-og-image-bars-are-in-the-wrong-order)</sub>

**Comment by PeterKwesiAnsah** [comment]
@mxkaske The screenshot link is not opening

**Comment by mxkaske** [comment]
Thanks @PeterKwesiAnsah. Maybe due to permission rights from Linear? Not sure as I can see it properly.

This one should work:
<img width="780" alt="CleanShot 2023-08-29 at 17 51 56@2x" src="https://github.com/openstatusHQ/openstatus/assets/56969857/8340d428-95c6-4023-9edc-78a77de7a8c3">

**Comment by PeterKwesiAnsah** [comment]
@mxkaske I can pick this up. Thanks

**Comment by mxkaske** [comment]
Hey @PeterKwesiAnsah, I have fixed the issue including some clean ups as well. If you want to have the next **good first issue** I can let you know.
