### ISSUE TITLE
[OPE-35] Create sitemap

### ISSUE THREAD

**Issue by mxkaske** [openstatusHQ/openstatus#26]
[https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap)

<sub>From [SyncLinear.com](https://synclinear.com) | [OPE-35](https://linear.app/openstatus/issue/OPE-35/create-sitemap)</sub>

**Comment by AmoabaKelvin** [comment]
I will like to take this up.

**Comment by mxkaske** [comment]
Amazing, thanks @AmoabaKelvin! 🔥

**Comment by mxkaske** [comment]
Added within #44.
