### ISSUE TITLE
If there is a monitor that hasn't been pinged a single time yet, and you add that to your status page, it crashes

### ISSUE THREAD

**Issue by zahid47** [openstatusHQ/openstatus#265]
To reproduce:

1. Create a new monitor with a long frequency.
2. Add that to your status page.
3. Visit your status page before it gets pinged.

I waited a few minutes for a ping and the page worked perfectly after that.

`Cannot read properties of undefined (reading 'cronTimestamp')`

![image](https://github.com/openstatusHQ/openstatus/assets/28688883/4e923ccd-28cb-4524-818f-4fd92e468eb8)

**Comment by mxkaske** [comment]
Thanks for reporting, @zahid47! It’s due to the latest changes in `Tracker.tsx`. 🥲
