### ISSUE TITLE
[Feature] Implement API endpoint that can be used for external diagnosis

### ISSUE THREAD

**Issue by ReduxMPX** [openstatusHQ/openstatus#282]
I'm super excited about this project, and we're planning to bring it into production.

However, what I've been in need of is an endpoint that can be called from the client that returns whether there are services that have a outage.
This way we can conditionally render a view that suggests visiting the status page to the user, if that endpoint does tell us that there is an issue.

**Comment by mxkaske** [comment]
Hey @ReduxMPX! Love it, thanks a lot for creating the feature request! 

We have considered that. To understand further, what do you expect from the endpoint to return?

We are thinking of having an `/public/status/[slug]` or `/public/widget/[slug]` endpoint where the slug is your status page slug. 

Would it be enough for you to share the current worst status for the monitors attached to the status page?

```ts
// simple
type ReturnProps = {
  status: "operational" | "degraded" | "down";
}
```

What I have in mind is something similar to resend where the simple return is enough.

<img width="470" alt="Screen Shot 2023-09-08 at 3 14 01 PM" src="https://github.com/openstatusHQ/openstatus/assets/56969857/2dbf5bae-1045-4ee2-89ae-6f6a86922321">

**Comment by ReduxMPX** [comment]
I agree! that's what I was envisioning. 
I think that simply having the three states is enough in almost all cases, and in my case I wouldn't actually need to know what monitors are affected.

Would love to see this in the future.

**Comment by mxkaske** [comment]
We have released an api route which you can use to access the current status of your status page via the unique `:slug`.

```
curl https://api.openstatus.dev/public/status/:slug
```

Read more: https://docs.openstatus.dev/api-server/status-widget
