### ISSUE TITLE
Export Shared components to own packages 

### ISSUE THREAD

**Issue by thibaultleouay** [openstatusHQ/openstatus#290]
components in app/web/src/components should be in packages/ui

**Comment by abdullah-25** [comment]
fixed it! Check my PR.

**Comment by thibaultleouay** [comment]
@abdullah-25  thanks for your work but i made a typo in the issue i meant only 

/Openstatus/apps/web/src/components/ui

These are shared UI components 
if you can update your pr that would be 🔥

**Comment by abdullah-25** [comment]
I made changes so now we have /Openstatus/apps/web/src/components/ui but there is another ui folder under packages. which ui do you want me to move under components?

**Comment by mxkaske** [comment]
Fixed in #309.
