### ISSUE TITLE
[OPE-19] Status Page

### ISSUE THREAD

**Issue by thibaultleouay** [openstatusHQ/openstatus#30]
<sub>From [SyncLinear.com](https://synclinear.com) | [OPE-19](https://linear.app/openstatus/issue/OPE-19/status-page)</sub>

**Comment by baguskna** [comment]
Hey, I would like to work on this issue. Is this open for everyone?

Thanks!

**Comment by nkilm** [comment]
@baguskna Please feel free to work on this issue, it is open for everyone🎉
