### ISSUE TITLE
Stuck in "Creating Workspace"

### ISSUE THREAD

**Issue by antoinekm** [openstatusHQ/openstatus#302]
Hey, i just signed up, and i'm stuck here, using Brave on MacOS:
<img width="1386" alt="image" src="https://github.com/openstatusHQ/openstatus/assets/54948363/c5ef9453-b6f3-412d-8c83-bad5ea02910c">
I got no errors in console just an infinite loading...

**Comment by mxkaske** [comment]
Hey @AntoineKM, thanks for pointing it out. Do you mind sharing us your email via [Discord dm](https://openstatus.dev/discord) so that we can have a look.

**Comment by hrutik7** [comment]
hey @mxkaske same for me 
windows 10 brave browser
![image](https://github.com/openstatusHQ/openstatus/assets/62372737/dd8a8d39-1c16-4cff-b132-289e4408700c)

**Comment by mxkaske** [comment]
Time to update the onboarding flow anyways. Thanks @hrutik7.

This issue most likely occurs while waiting for clerks ‘created user’ webhook to trigger a workspace creation but are not getting any response.

**Comment by DevangGarg** [comment]
The onboarding flow may be not brave browser compatible. Need to check in the documentation of the clerk for any other hack to resolve this creating workspace issue.

**Comment by antoinekm** [comment]
i got the same issue on Safari and Firefox using MacOS

**Comment by AmoabaKelvin** [comment]
Once you check on your clerk dashboard, you should see it under the webhooks session, the call that was made to the ngrok url provided.

You will see a type of `user.created`, click on it, copy the contents of the payload and manually make a `POST` request using the copied payload to the API endpoint where we create the user locally, `http://localhost:3000/api/clerk`

This should create the user instance in the local `turso` database and redirect you to the app screen.

**Comment by antoinekm** [comment]
On my side i didnt installed the project locally i'm just using https://openstatus.dev/ and it happen on `https://openstatus.dev/app` route

**Comment by AmoabaKelvin** [comment]
Thanks for the clarification @AntoineKM 
We'll look into it ASAP

**Comment by hrutik7** [comment]
> Once you check on your clerk dashboard, you should see it under the webhooks session, the call that was made to the ngrok url provided.
> 
> You will see a type of `user.created`, click on it, copy the contents of the payload and manually make a `POST` request using the copied payload to the API endpoint where we create the user locally, `http://localhost:3000/api/clerk`
> 
> This should create the user instance in the local `turso` database and redirect you to the app screen.

thanks ! I followed this and it's working for me

**Comment by mxkaske** [comment]
The `workspaceSlug` is always generated automatically. It has to be unique for every user. Until now, we had no check if the generated slug already exists. We re-generate the slug until it's unique. That can be a cause for the issue.

We also added an onboarding flow in #310. It might not have fixed the issue - but updated the page and included a link to discord for asking  for help.

I will close it. We can reopen it if it reappears.
