### ISSUE TITLE
Feature request: custom favicon

### ISSUE THREAD

**Issue by zackrw** [openstatusHQ/openstatus#312]
Similar to linearstatus.com on incident.io

**Comment by mxkaske** [comment]
What do you mean exactly? We support favicon uploads.

https://github.com/openstatusHQ/openstatus/blob/c177d8e17bb2e62ece251a3761fe1b9fd8e6292e/apps/web/src/components/forms/status-page-form.tsx#L248

**Comment by zackrw** [comment]
I simply failed to see it. Thanks for building even before I thought of it :) 

On the bright side I found and fixed a tiny typo while investigating: https://github.com/openstatusHQ/openstatus/pull/319
