### ISSUE TITLE
Infinite redirects after signup + other errors running locally

### ISSUE THREAD

**Issue by zackrw** [openstatusHQ/openstatus#315]
I've followed instructions in setup-env.mdx and things are mostly working, but I see this in my console:
<img width="380" alt="Captura de pantalla 2023-09-19 a la(s) 12 11 33 p m" src="https://github.com/openstatusHQ/openstatus/assets/954970/e3e4bbdf-e356-423c-8d0a-6938f6f44502">

And this on my screen after signing up:
<img width="624" alt="Captura de pantalla 2023-09-19 a la(s) 12 14 08 p m" src="https://github.com/openstatusHQ/openstatus/assets/954970/12be58bc-711f-4c57-ac1a-db4626a3ed86">

It refreshes ever 1000ms per the setTimeout on the page. There is no other logging, and this is for a cloud turso.tech instance. I tried manually creating the workspace record in Turso and then navigating to that slug, but this leads to an "Error: Unexpected token N in JSON at position 4" error.

<img width="1204" alt="Captura de pantalla 2023-09-19 a la(s) 12 16 45 p m" src="https://github.com/openstatusHQ/openstatus/assets/954970/ddb8f391-0dd0-4ff4-af54-62e5d17670e3">

Thanks for your help!

**Comment by AmoabaKelvin** [comment]
Hello @zackrw 
Thanks for reporting this!

Let me try and assist you over here, but in case you want to hang out with the family more, you can join our discord server @ https://www.openstatus.dev/discord

Do you have an ngrok tunnel running and pointing to port 3000 (the port for the web application) ?

**Comment by AmoabaKelvin** [comment]
We have a cool thread on using clerk webhook in our discord, once you join in, you can use this link to navigate to it.
https://discord.com/channels/1129008226264940625/1137824211008761977

**Comment by zackrw** [comment]
Thanks! I was able to get the webhook working, I'll follow up in Discord on the rest of it.
