### ISSUE TITLE
INVALID ENVIRONMENTAL VARIABLES

### ISSUE THREAD

**Issue by PeterKwesiAnsah** [openstatusHQ/openstatus#330]
I have being getting this error anytime  I try to spun up the local server for the web app

![Screenshot (53)](https://github.com/openstatusHQ/openstatus/assets/31078314/7bb7c1d2-4435-49e1-a2d1-368f3392be66)

**Comment by zahid47** [comment]
You need to copy the `.env.example` from `apps/web` and create a new `.env` file.  And for sign-up to work, you need to fill `NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY` and `CLERK_SECRET_KEY`. You can get them from your clerk dashboard.
