### ISSUE TITLE
Terraform provider

### ISSUE THREAD

**Issue by thibaultleouay** [openstatusHQ/openstatus#333]
Create a Terraform provider to create monitors

**Comment by sahilthakral23** [comment]
Hi @thibaultleouay , I would like to pick this up. Is anyone currently working on it or can I pick it up ?

Also a different repository will be needed for the terraform-provider code. So do let me know your thoughts on the same.

**Comment by sahilthakral23** [comment]
Hello @thibaultleouay, just checking up again on this. Do let me know your thoughts on the same

**Comment by thibaultleouay** [comment]
@sahilthakral23  I have created a new repo for this 

https://github.com/openstatusHQ/terraform-provider-openstatus 

Let's continue there
