### ISSUE TITLE
[OPE-47] Setup I18n

### ISSUE THREAD

**Issue by thibaultleouay** [openstatusHQ/openstatus#34]
Allow different locales

<sub>From [SyncLinear.com](https://synclinear.com) | [OPE-47](https://linear.app/openstatus/issue/OPE-47/setup-i18n)</sub>

**Comment by theprogrammerinyou** [comment]
Hi, can i work on this? Can you assign me to this?

**Comment by hrutik7** [comment]
hey @thibaultleouay is this issue still relevent ?

**Comment by mxkaske** [comment]
Hey @hrutik7! #318 is a first approach to include i18n. I'll check for another issue that you can tackle. 💪
