### ISSUE TITLE
ui bug: green uptime bars get greyed out on the status page when switching to the incidents page

### ISSUE THREAD

**Issue by SeanCassiere** [openstatusHQ/openstatus#340]
When you visit a status page and switch tabs from "Status" to "Incidents", and then back from "Incidents" to the "Status" tab, some of the green uptime bars on the monitors towards the right of the screen get greyed out.

I observed this behaviour on my status page: [seancassiere.openstatus.dev](https://seancassiere.openstatus.dev)

The same behaviour occurs on Chrome, Arc, Firefox, and Safari. See the screenshots below.

Reproduction steps:
1. Visit a configured status page.
<img width="1680" alt="image" src="https://github.com/openstatusHQ/openstatus/assets/33615041/377fc0f7-3f73-4e15-a2fe-f5141c740812">

2. Switch to the "Incidents" tab.
3. Switch back to the "Status" tab.
<img width="1679" alt="image" src="https://github.com/openstatusHQ/openstatus/assets/33615041/a350eaff-6bc4-4fbc-8070-c6548cb36a95">

**Comment by mxkaske** [comment]
Hey @SeanCassiere! 

Thanks for letting us know. This is very unfortunate. On my end, I coudn't reproduce the issue on any status page. I have tested it on multiple devices and browsers.

Does it appear on other status pages for you? Like:
- https://status.documenso.com
- https://status.openstatus.dev

**Comment by SeanCassiere** [comment]
<details><summary>status.documenso.com</summary>
<p>
<img width="1680" src="https://github.com/openstatusHQ/openstatus/assets/33615041/9288522b-0ff5-4a7d-9399-3837590d2cfe" alt="image" />
</p>
</details> 

<details><summary>status.openstatus.dev</summary>
<p>
<img width="1680" src="https://github.com/openstatusHQ/openstatus/assets/33615041/53e0f549-b765-4321-859b-ff59f5138c96" alt="image" />
</p>
</details> 

I'm on the new version of MacOS (Sonoma), I'll be sure to give my machine a restart and confirm.

**Comment by SeanCassiere** [comment]
Just gave my machine a restart and can confirm it's still happening for me.
<img width="1680" alt="image" src="https://github.com/openstatusHQ/openstatus/assets/33615041/6184f736-68f4-415a-b0d4-d5ce761bd5ab">

**Comment by mxkaske** [comment]
Ok, thanks for the confirmation! Will investigate further.

**Comment by mxkaske** [comment]
Hey @SeanCassiere, I'm still very much confused as we haven't been able to reproduce this issue.

**Comment by SeanCassiere** [comment]
> Hey @SeanCassiere, I'm still very much confused as we haven't been able to reproduce this issue.

I wish I could chalk it up to it just being a MacOS bug or something, but I just tried it on my Android phone in Chrome they also get greyed out.
<details><summary>Screenshots</summary>
<p>
<img src="https://github.com/openstatusHQ/openstatus/assets/33615041/04f9bf80-a3ff-42b3-9b46-4e39804077f5" alt="Screenshot_2023-10-02-04-16-48-55_40deb401b9ffe8e1df2f1cc5ba480b12.jpg" />
<img src="https://github.com/openstatusHQ/openstatus/assets/33615041/c42e6a36-c02f-4914-8386-8b10a89264b7" alt="Screenshot_2023-10-02-04-17-08-15_40deb401b9ffe8e1df2f1cc5ba480b12.jpg" />
</p>
</details>

**Comment by SeanCassiere** [comment]
Not sure if this plays a role or not, but upon switching to the incidents tab and back there are a few 404 requests.

This is the URL that returns a 404, [https://seancassiere.openstatus.dev/monitoring?o=4505782661349376&p=4505782662791168](https://seancassiere.openstatus.dev/monitoring?o=4505782661349376&p=4505782662791168)

EDIT1: This is with AdBlock turned off.
EDIT2: One thing I just noticed. Yesterday when I posted the screenshots, there were **7** bars on the right greyed out. Today, there are **8** bars on the right greyed out.

<details><summary>Before</summary>
<p>
<img width="1680" src="https://github.com/openstatusHQ/openstatus/assets/33615041/2124ad45-0485-4cf7-88fb-db720e557324" alt="image" />
</p>
</details>

<details><summary>After</summary>
<p>
<img width="1680" src="https://github.com/openstatusHQ/openstatus/assets/33615041/e660eb76-c92c-42c1-9351-91175e0344d5" alt="image" />
</p>
</details>

**Comment by mxkaske** [comment]
I'm also getting the `404` errors because for some reasons, we are trying to access the `/app/sign-in` path that is not existent because of our "status-page" redirects. That definitely needs to get fixed but I is not the root cause of the greyed out bars unfortunate.

**Comment by SeanCassiere** [comment]
I'll try and source a device which I've never used tomorrow to try and visit the documenso page.

> Did a few checks today as well. AdBlock is disabled and in Incognito.

## Checking today for status.documenso.com
The number of bars greyed out has gone up for me, last time two days ago it was 8, and today it stands at 10.


<img width="586" alt="image" src="https://github.com/openstatusHQ/openstatus/assets/33615041/8c76b585-60ff-4287-88a6-8567d2c93101">

This increase persists across all three pages I tried.

## Checking today for status.openstatus.com
Today, I also noticed that the status page for openstatus loads the page with the bars correctly filled out, and then flickers with the last 10 getting greyed out. This also happened for the documenso status page, but not my personal page.

Screen capture for [status.openstatus.dev](https://status.openstatus.dev): [https://drive.google.com/file/d/1W-v4lrf3MBeb7ZL1xCx3IkfL1pswYGwI/view?usp=sharing](https://drive.google.com/file/d/1W-v4lrf3MBeb7ZL1xCx3IkfL1pswYGwI/view?usp=sharing)

These were the errors in the console (that were not the Clerk related auth errors).
<details><summary>First error</summary>
<pre>
Uncaught Error: Minified React error #425; visit https://reactjs.org/docs/error-decoder.html?invariant=425 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at sD (43d26fe7-a74ecc6f5193f7d3.js:9:146469)
    at 43d26fe7-a74ecc6f5193f7d3.js:9:100999
    at oe (43d26fe7-a74ecc6f5193f7d3.js:9:103845)
    at i5 (43d26fe7-a74ecc6f5193f7d3.js:9:95154)
    at 43d26fe7-a74ecc6f5193f7d3.js:9:91330
    at 43d26fe7-a74ecc6f5193f7d3.js:9:91337
    at iH (43d26fe7-a74ecc6f5193f7d3.js:9:91442)
    at MessagePort.R (3462-c2377369977a32ab.js:30:1665)
</pre>
</details> 
<details><summary>Second error</summary>
<pre>
Uncaught Error: Minified React error #422; visit https://reactjs.org/docs/error-decoder.html?invariant=422 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at 43d26fe7-a74ecc6f5193f7d3.js:9:64246
    at lK (43d26fe7-a74ecc6f5193f7d3.js:9:65611)
    at oB (43d26fe7-a74ecc6f5193f7d3.js:9:121034)
    at i5 (43d26fe7-a74ecc6f5193f7d3.js:9:95093)
    at 43d26fe7-a74ecc6f5193f7d3.js:9:91330
    at 43d26fe7-a74ecc6f5193f7d3.js:9:91337
    at iH (43d26fe7-a74ecc6f5193f7d3.js:9:91442)
    at MessagePort.R (3462-c2377369977a32ab.js:30:1665)
</pre>
</details> 

## Checking for seancassiere.openstatus.dev
The flickering above, was not present when I checked it on my own page. It had the original behaviour for triggering the ui bug by navigating to the incidents page.

Screen capture for [seancassiere.openstatus.dev](seancassiere.openstatus.dev) : [https://drive.google.com/file/d/1x6BQmVk0kHEXZUIUhbS_k-TxuyQ6kUba/view?usp=sharing](https://drive.google.com/file/d/1x6BQmVk0kHEXZUIUhbS_k-TxuyQ6kUba/view?usp=sharing)

**Comment by SeanCassiere** [comment]
As mentioned yesterday, I checked it on a separate device today, and it persists. The only common variable between my device and the one I used today, is the ISP.

<details><summary>Screenshot</summary>
<p>
<img src="https://github.com/openstatusHQ/openstatus/assets/33615041/3e00092d-5373-4dc0-9d82-f1fcd278b872" alt="WhatsApp Image 2023-10-04 at 22 42 07">
</p>
</details> 

And today it is up to 11 bars.

**Comment by SeanCassiere** [comment]
Checked on this today, and this seems to be resolved. Not sure if this is due to me currently being in Sri Lanka, but it seems to be fixed.
<img width="1680" alt="image" src="https://github.com/openstatusHQ/openstatus/assets/33615041/380db8b1-a660-47f1-96d5-20ee7873a523">

**Comment by mxkaske** [comment]
Interesting, I can only assume this to be a timezone issue.

**Comment by SeanCassiere** [comment]
> Interesting, I can only assume this to be a timezone issue.

Could be the culprit.

I won't be back in New Zealand for a couple more weeks, but will update once I'm in country.

**Comment by thibaultleouay** [comment]
@SeanCassiere  we found the issue it was timezone related and it's fixed with #469
