### ISSUE TITLE
[OPE-22] Add GitHub Actions

### ISSUE THREAD

**Issue by mxkaske** [openstatusHQ/openstatus#35]
* tsc
* lint
* …

<sub>From [SyncLinear.com](https://synclinear.com) | [OPE-22](https://linear.app/openstatus/issue/OPE-22/add-github-actions)</sub>

**Comment by AmoabaKelvin** [comment]
Hello @mxkaske , since I got the sitemaps PR merged, I will love to take this on.

**Comment by thibaultleouay** [comment]
@AmoabaKelvin sure that would be awesome

Imo At the beginning the GitHub action should lint and prettier 

If you think of something else feel free to add it
