### ISSUE TITLE
[OPE-38] Notification System

### ISSUE THREAD

**Issue by mxkaske** [openstatusHQ/openstatus#36]
Whenever a ping is **not** `200`\-`299`, we should send a notification to the user.

Before starting, we should make sure to have a stable API around that.

For each integration, we should have a `mapping` function from our API to the service one.

<sub>From [SyncLinear.com](https://synclinear.com) | [OPE-38](https://linear.app/openstatus/issue/OPE-38/notification-system)</sub>

**Comment by jzambrano12** [comment]
Can I work on this feature?

**Comment by mxkaske** [comment]
Let's move it to done!
