### ISSUE TITLE
Bug: Wrong time shown in graph

### ISSUE THREAD

**Issue by stefanes** [openstatusHQ/openstatus#369]
Looks like the graph is using UTC instead of browser time?

![image](https://github.com/openstatusHQ/openstatus/assets/5484354/17e9c65f-aa23-492d-be40-28810e4df87e)

**Comment by 0xJaskeerat** [comment]
Hey @stefanes if am not wrong 
<code>Oct 12, 2023 22:50</code>  is the UTC time ?
<code> 08:50 pm </code> is the time at your place ?

**Comment by stefanes** [comment]
I'm in the CET (UTC+2) time zone, `22:50` was my local time in this example.
https://time.is/compare/2250_12_Oct_2023_in_CET/UTC

**Comment by 0xJaskeerat** [comment]
> I'm in the CET (UTC+2) time zone, `22:50` was my local time in this example. https://time.is/compare/2250_12_Oct_2023_in_CET/UTC

@mxkaske What do you think , should we be preferring the UTC time or the browser time of the user
According to me maybe we can use the browser time of the user , and also add a ToolTip on that to show the UTC time
or maybe send that time to any sort of backend involved , also while retrieval from backend , we can convert it back according to user's current time

What do you think of this ?

**Comment by mxkaske** [comment]
Hey guys! 

I think there is a misalignement between the 'server' and 'client' `timestamp`. One is formatted on the server (graph), the other one on the client (table).

Thanks @0xJaskeerat for your remark here! Tbh, I think we should consider the formatting of dates **only** on the client to avoid those errors and because it is accurate to the users location and timezone. Then, we don't need to think about a workaround.

**Comment by 0xJaskeerat** [comment]
> Hey guys!
> 
> I think there is a misalignement between the 'server' and 'client' `timestamp`. One is formatted on the server (graph), the other one on the client (table).
> 
> Thanks @0xJaskeerat for your remark here! Tbh, I think we should consider the formatting of dates **only** on the client to avoid those errors and because it is accurate to the users location and timezone. Then, we don't need to think about a workaround.

So, I guess it boils down to storing the time as UTC in the backend and formatting only when retrieve & display the time on the frontend / client side 

Anyways I would love to contribute to this , can you assign this to me ?

**Comment by stefanes** [comment]
This seems to have been fixed now. But is it possible to also get the time format to be the same? We use 24h time where I live, so the tables is again correct and graph is not. 

![image](https://github.com/openstatusHQ/openstatus/assets/5484354/ef960fe7-afd3-4bf8-8d05-9a7062699f49)
