### ISSUE TITLE
Feture request: Disable/pause monitors

### ISSUE THREAD

**Issue by stefanes** [openstatusHQ/openstatus#372]
Would be nice to be able to disable/pause monitors instead of deleting them. Could still count against the plans monitor quota, would still be valid in some cases.

**Comment by mxkaske** [comment]
It is accessible inside of the **Advanced Settings**. We should make it more obvious. Fair point with quota. Right now we are not differentiating disabled/enabled monitors for that.

**Comment by stefanes** [comment]
Ah, sorry! Should have found that myself. Was looking for it on the ... menu.

**Comment by mxkaske** [comment]
No that's good! We will make it more visible.

**Comment by mxkaske** [comment]
Keeping it open as a reminder/task!
