### ISSUE TITLE
Feature request: Upside down mode

### ISSUE THREAD

**Issue by stefanes** [openstatusHQ/openstatus#373]
Would love to have the ability to have a monitor that alerts if an endpoint is accessible, that is the other way around from what you can do now. One possible use case would be to check that a firewall is up and preventing access from outside of a region/country.

An alternative to this would be to be able to select which response codes to accept as OK, like one or more of:
- `200-299`
- `300-399`
- `400-499`
- `500-599`

**Comment by mxkaske** [comment]
Cool! The goal is to move more into incident workflows and that will be part of it.

**Comment by thibaultleouay** [comment]
@stefanes  we are going to add some custom assertion in the coming weeks #660

**Comment by thibaultleouay** [comment]
@stefanes  we have implemented assertions which should solved it
