### ISSUE TITLE
[OPE-41] Integrate Email

### ISSUE THREAD

**Issue by mxkaske** [openstatusHQ/openstatus#38]
<sub>From [SyncLinear.com](https://synclinear.com) | [OPE-41](https://linear.app/openstatus/issue/OPE-41/integrate-email)</sub>

**Comment by thibaultleouay** [comment]
It's for the alerting system we should send email if there's a failure

**Comment by shawshankkumar** [comment]
Hey! How can i help with this?

**Comment by mxkaske** [comment]
Keeping it open until resolved
