### ISSUE TITLE
Feature Request: Ability to Ping IP adresses

### ISSUE THREAD

**Issue by 0pilatos0** [openstatusHQ/openstatus#380]
I would like to request the addition of IP pinging support as a monitoring method in your status page product. This feature would enable users to monitor the availability of servers that do not have HTTP GET/POST endpoints. Here's why I believe this feature would be valuable:

**Use Case:**
I utilize multiple outgoing traffic-only servers that exclusively send information and do not host any HTTP endpoints. In such scenarios, performing HTTP GET/POST requests is not applicable or efficient. IP ping, on the other hand, is a more suitable method to ensure the servers' availability as it doesnt require any webservers to be running

(edit): Although im not familiar with the codebase i would be open to contribute if needed

**Comment by thibaultleouay** [comment]
@0pilatos0  do you have some sample IP address I could test it against?

**Comment by 0pilatos0** [comment]
@thibaultleouay Hey, any ip should be able to work.

- 8.8.8.8  (google dns)
- 8.8.4.4 (another google dns)
- 37.235.1.174 (freedns server)

but i think also the domain should work with a ping

- google.com
- freedns.afraid.org

just like the terminal `ping <ip>` command

(EDIT): you could be running into issues with server that [disabled ping](https://unix.stackexchange.com/questions/412446/how-to-disable-ping-response-icmp-echo-in-linux-all-the-time) but thats a small edgecase i think can not be handled

**Comment by thibaultleouay** [comment]
@0pilatos0  we have introduced TCP monitoring it should solved this
