### ISSUE TITLE
Bug: Notifications are not working

### ISSUE THREAD

**Issue by stefanes** [openstatusHQ/openstatus#383]
Notifications are not working currently, follow discussion here: https://discord.com/channels/1129008226264940625/1162131935301222521

### Actual behaviour

I created a monitor to a non-existing URL, expecting a notification being sent after the configured amount retries. I also tried to first set it to a working URL, so I get a nice `200` response to start with, and later changing to a non existing URL - still no notification.

### Expected behaviour

Notification is sent after initial failure and the configured amount of retries.

**Comment by thibaultleouay** [comment]
This has bee resolved in #437
