### ISSUE TITLE
Some fetch are failing for some url

### ISSUE THREAD

**Issue by thibaultleouay** [openstatusHQ/openstatus#406]
For some url we can't not resolve DNS 

It's a Bun issue
https://github.com/oven-sh/bun/issues/6658

**Comment by AshutoshNanaware** [comment]
Hello @thibaultleouay ,
I've reviewed the discussion on this issue, and it appears there is no conclusive resolution. Is there anything specific I can assist with to move this matter forward?

**Comment by thibaultleouay** [comment]
We have moved the checker to golang and now it's working perfectly 😁

**Comment by AshutoshNanaware** [comment]
That's great, although the issue was interesting.

**Comment by thibaultleouay** [comment]
we are using go that solved the issue

**Comment by AshutoshNanaware** [comment]
The issue was about to hit an anniversary 😀.
