### ISSUE TITLE
Bug: Initial ping when creating a monitor seems to not use selected HTTP method

### ISSUE THREAD

**Issue by stefanes** [openstatusHQ/openstatus#409]
### Preliminary Checks

- [X] I have reviewed the documentation: https://docs.openstatus.dev/

- [X] I have searched for existing issues: https://github.com/openstatusHQ/openstatus/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to OpenStatus. Please ask questions in our Discord community: https://www.openstatus.dev/discord

### Description

**Steps to reproduce:**

1. Create a new monitor for a host that only allows HEAD requests
2. Set the HTTP method to **HEAD** under _HTTP Request Settings_
3. Click **Create**

**Expected behavior:**

Initial ping is performed using the selected method and the monitor is created without any warning displayed to the user.

**Actual behavior:**

The initial ping request seems to not use the method selected under _HTTP Request Settings_, and a warning is displayed to the user:

![image](https://github.com/openstatusHQ/openstatus/assets/5484354/0f0ef087-02ce-4668-a8b2-895e008221b9)

**Comment by AmoabaKelvin** [comment]
Thank you @stefanes for reporting this. Will jump into fixing that ASAP

**Comment by stefanes** [comment]
Same issue seems to be true for the _Test endpoint_ functionality btw:

![image](https://github.com/openstatusHQ/openstatus/assets/5484354/9efda0c7-f46e-4fbb-8ced-85903a9fba5d)

**Comment by AmoabaKelvin** [comment]
Hey @stefanes, issue identified and fixed, should be okay once we merge and deploy 🚀 

Cheers, 🥂
