### ISSUE TITLE
Last Monitor Check Time made on Status Page

### ISSUE THREAD

**Issue by arshkkk** [openstatusHQ/openstatus#417]
### Preliminary Checks

- [X] I have reviewed https://docs.openstatus.dev/ for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/openstatusHQ/openstatus/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to OpenStatus. Please ask questions in our Discord community: https://discord.com/invite/dHD4JtSfsn.

### Description

It would be insightful for user to see last time endpoint/monitor was checked on stage page 
Something like

`Updated 2 minutes ago` or `Updated an hour ago` something like that

**Comment by mxkaske** [comment]
Good idea!

**Comment by thibaultleouay** [comment]
If your monitor is public you can see this information 
e.g.
https://status.openstatus.dev/monitors/1
