### ISSUE TITLE
Brave Errors and Issues?

### ISSUE THREAD

**Issue by aanomm** [openstatusHQ/openstatus#421]
**Steps to reproduce:**

1. Load Status page

**Expected behavior:**

See only current and past dates in the data/bar-graph

**Actual behavior:**

See future dates in the data/bar-graph

![image](https://github.com/openstatusHQ/openstatus/assets/1171169/f311c38a-4701-4c90-858d-39137d1c7ccc)

Note 1: On page load there's a split-second view of the expected view (only current and past dates) but then it instantly reverts to showing future dates too

Note 2: This only seems to happen in Brave (with the Brave Shield turned Off and On); I tested in Edge and it works as expected

**Console Errors**

74 Unchecked runtime.lastError: The message port closed before a response was received.
6ae2e73d-56dc390bd4571847.js:9 Uncaught Error: Minified React error #425; visit https://reactjs.org/docs/error-decoder.html?invariant=425 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at sD (6ae2e73d-56dc390bd4571847.js:9:146469)
    at 6ae2e73d-56dc390bd4571847.js:9:100999
    at oe (6ae2e73d-56dc390bd4571847.js:9:103845)
    at i5 (6ae2e73d-56dc390bd4571847.js:9:95154)
    at 6ae2e73d-56dc390bd4571847.js:9:91330
    at 6ae2e73d-56dc390bd4571847.js:9:91337
    at iH (6ae2e73d-56dc390bd4571847.js:9:91442)
    at MessagePort.R (1267-4ab0ec8e09d20fc2.js:30:1665)
sD @ 6ae2e73d-56dc390bd4571847.js:9
(anonymous) @ 6ae2e73d-56dc390bd4571847.js:9
oe @ 6ae2e73d-56dc390bd4571847.js:9
i5 @ 6ae2e73d-56dc390bd4571847.js:9
(anonymous) @ 6ae2e73d-56dc390bd4571847.js:9
(anonymous) @ 6ae2e73d-56dc390bd4571847.js:9
iH @ 6ae2e73d-56dc390bd4571847.js:9
R @ 1267-4ab0ec8e09d20fc2.js:30
6ae2e73d-56dc390bd4571847.js:9 Uncaught Error: Minified React error #422; visit https://reactjs.org/docs/error-decoder.html?invariant=422 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at 6ae2e73d-56dc390bd4571847.js:9:64246
    at lK (6ae2e73d-56dc390bd4571847.js:9:65611)
    at oB (6ae2e73d-56dc390bd4571847.js:9:121034)
    at i5 (6ae2e73d-56dc390bd4571847.js:9:95093)
    at 6ae2e73d-56dc390bd4571847.js:9:91330
    at 6ae2e73d-56dc390bd4571847.js:9:91337
    at iH (6ae2e73d-56dc390bd4571847.js:9:91442)
    at MessagePort.R (1267-4ab0ec8e09d20fc2.js:30:1665)
(anonymous) @ 6ae2e73d-56dc390bd4571847.js:9
lK @ 6ae2e73d-56dc390bd4571847.js:9
oB @ 6ae2e73d-56dc390bd4571847.js:9
i5 @ 6ae2e73d-56dc390bd4571847.js:9
(anonymous) @ 6ae2e73d-56dc390bd4571847.js:9
(anonymous) @ 6ae2e73d-56dc390bd4571847.js:9
iH @ 6ae2e73d-56dc390bd4571847.js:9
R @ 1267-4ab0ec8e09d20fc2.js:30
1267-4ab0ec8e09d20fc2.js:1 
        
        
       POST https://status.openstatus.dev/app/sign-in?redirect_url=https%3A%2F%2Fstatus.openstatus.dev%2Fmonitoring%3Fo%3D4505782661349376%26p%3D4505782662791168 404 (Not Found)
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
add @ 1267-4ab0ec8e09d20fc2.js:1
a @ 1267-4ab0ec8e09d20fc2.js:1
_sendEnvelope @ 1267-4ab0ec8e09d20fc2.js:1
sendSession @ 1267-4ab0ec8e09d20fc2.js:1
captureSession @ 1267-4ab0ec8e09d20fc2.js:1
_sendSessionUpdate @ 1267-4ab0ec8e09d20fc2.js:1
captureSession @ 1267-4ab0ec8e09d20fc2.js:1
eY @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
tY @ 1267-4ab0ec8e09d20fc2.js:1
67570 @ main-app-9729259e2d8c0b9f.js:1
l @ webpack-6cffb47ac2ee2426.js:1
E @ main-app-9729259e2d8c0b9f.js:1
(anonymous) @ main-app-9729259e2d8c0b9f.js:1
l.O @ webpack-6cffb47ac2ee2426.js:1
c @ webpack-6cffb47ac2ee2426.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
1267-4ab0ec8e09d20fc2.js:1 
        
        
       POST https://status.openstatus.dev/app/sign-in?redirect_url=https%3A%2F%2Fstatus.openstatus.dev%2Fmonitoring%3Fo%3D4505782661349376%26p%3D4505782662791168 404 (Not Found)
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
add @ 1267-4ab0ec8e09d20fc2.js:1
a @ 1267-4ab0ec8e09d20fc2.js:1
_sendEnvelope @ 1267-4ab0ec8e09d20fc2.js:1
sendEvent @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
_executeHandlers @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
u @ 1267-4ab0ec8e09d20fc2.js:1
then @ 1267-4ab0ec8e09d20fc2.js:1
_processEvent @ 1267-4ab0ec8e09d20fc2.js:1
_captureEvent @ 1267-4ab0ec8e09d20fc2.js:1
captureEvent @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
_withClient @ 1267-4ab0ec8e09d20fc2.js:1
captureEvent @ 1267-4ab0ec8e09d20fc2.js:1
eu @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
g @ 1267-4ab0ec8e09d20fc2.js:1
f.onerror @ 1267-4ab0ec8e09d20fc2.js:1
a @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 6ae2e73d-56dc390bd4571847.js:9
ot @ 6ae2e73d-56dc390bd4571847.js:9
iY @ 6ae2e73d-56dc390bd4571847.js:9
iH @ 6ae2e73d-56dc390bd4571847.js:9
R @ 1267-4ab0ec8e09d20fc2.js:30
error (async)
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
_ @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
tD @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
tY @ 1267-4ab0ec8e09d20fc2.js:1
67570 @ main-app-9729259e2d8c0b9f.js:1
l @ webpack-6cffb47ac2ee2426.js:1
E @ main-app-9729259e2d8c0b9f.js:1
(anonymous) @ main-app-9729259e2d8c0b9f.js:1
l.O @ webpack-6cffb47ac2ee2426.js:1
c @ webpack-6cffb47ac2ee2426.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
1267-4ab0ec8e09d20fc2.js:1 
        
        
       POST https://status.openstatus.dev/app/sign-in?redirect_url=https%3A%2F%2Fstatus.openstatus.dev%2Fmonitoring%3Fo%3D4505782661349376%26p%3D4505782662791168 404 (Not Found)
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
add @ 1267-4ab0ec8e09d20fc2.js:1
a @ 1267-4ab0ec8e09d20fc2.js:1
_sendEnvelope @ 1267-4ab0ec8e09d20fc2.js:1
sendSession @ 1267-4ab0ec8e09d20fc2.js:1
captureSession @ 1267-4ab0ec8e09d20fc2.js:1
_updateSessionFromEvent @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
_executeHandlers @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
u @ 1267-4ab0ec8e09d20fc2.js:1
then @ 1267-4ab0ec8e09d20fc2.js:1
_processEvent @ 1267-4ab0ec8e09d20fc2.js:1
_captureEvent @ 1267-4ab0ec8e09d20fc2.js:1
captureEvent @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
_withClient @ 1267-4ab0ec8e09d20fc2.js:1
captureEvent @ 1267-4ab0ec8e09d20fc2.js:1
eu @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
g @ 1267-4ab0ec8e09d20fc2.js:1
f.onerror @ 1267-4ab0ec8e09d20fc2.js:1
a @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 6ae2e73d-56dc390bd4571847.js:9
ot @ 6ae2e73d-56dc390bd4571847.js:9
iY @ 6ae2e73d-56dc390bd4571847.js:9
iH @ 6ae2e73d-56dc390bd4571847.js:9
R @ 1267-4ab0ec8e09d20fc2.js:30
error (async)
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
_ @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
tD @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
tY @ 1267-4ab0ec8e09d20fc2.js:1
67570 @ main-app-9729259e2d8c0b9f.js:1
l @ webpack-6cffb47ac2ee2426.js:1
E @ main-app-9729259e2d8c0b9f.js:1
(anonymous) @ main-app-9729259e2d8c0b9f.js:1
l.O @ webpack-6cffb47ac2ee2426.js:1
c @ webpack-6cffb47ac2ee2426.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
1267-4ab0ec8e09d20fc2.js:1 
        
        
       POST https://status.openstatus.dev/app/sign-in?redirect_url=https%3A%2F%2Fstatus.openstatus.dev%2Fmonitoring%3Fo%3D4505782661349376%26p%3D4505782662791168 404 (Not Found)
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
add @ 1267-4ab0ec8e09d20fc2.js:1
a @ 1267-4ab0ec8e09d20fc2.js:1
_sendEnvelope @ 1267-4ab0ec8e09d20fc2.js:1
sendEvent @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
_executeHandlers @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
u @ 1267-4ab0ec8e09d20fc2.js:1
then @ 1267-4ab0ec8e09d20fc2.js:1
_processEvent @ 1267-4ab0ec8e09d20fc2.js:1
_captureEvent @ 1267-4ab0ec8e09d20fc2.js:1
captureEvent @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
_withClient @ 1267-4ab0ec8e09d20fc2.js:1
captureEvent @ 1267-4ab0ec8e09d20fc2.js:1
eu @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
g @ 1267-4ab0ec8e09d20fc2.js:1
f.onerror @ 1267-4ab0ec8e09d20fc2.js:1
a @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 6ae2e73d-56dc390bd4571847.js:9
ot @ 6ae2e73d-56dc390bd4571847.js:9
iY @ 6ae2e73d-56dc390bd4571847.js:9
iH @ 6ae2e73d-56dc390bd4571847.js:9
R @ 1267-4ab0ec8e09d20fc2.js:30
error (async)
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
_ @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
tD @ 1267-4ab0ec8e09d20fc2.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
tY @ 1267-4ab0ec8e09d20fc2.js:1
67570 @ main-app-9729259e2d8c0b9f.js:1
l @ webpack-6cffb47ac2ee2426.js:1
E @ main-app-9729259e2d8c0b9f.js:1
(anonymous) @ main-app-9729259e2d8c0b9f.js:1
l.O @ webpack-6cffb47ac2ee2426.js:1
c @ webpack-6cffb47ac2ee2426.js:1
(anonymous) @ 1267-4ab0ec8e09d20fc2.js:1
1267-4ab0ec8e09d20fc2.js:1 
        
        
       POST https://status.openstatus.dev/app/sign-in?redirect_url=https%3A%2F%2Fstatus.openstatus.dev%2Fmonitoring%3Fo%3D4505782661349376%26p%3D4505782662791168 404 (Not Found)

**Comment by thibaultleouay** [comment]
![CleanShot 2023-10-30 at 09 12 27](https://github.com/openstatusHQ/openstatus/assets/13894054/fb5970cd-ee21-46ea-8452-ce643deeb87a)
Just tried it with brave and it was ok 
Im investigating it

**Comment by mxkaske** [comment]
Might be related to #340.

**Comment by mxkaske** [comment]
@fucha-co, where are you located, this might be a timezone issue.

**Comment by thibaultleouay** [comment]
@fucha-co  it's solved with #469

**Comment by aanomm** [comment]
> @fucha-co, where are you located, this might be a timezone issue.

- sorry i didn't get a Github notification about your mention; i am located in AU (Australia) 
- and the official Open Status Status page now appears as expected for my (visually) so maybe it was a timezone issue
- thanks for your time and fab tool...
