### ISSUE TITLE
Endpoint Latency on status page with P95, P75, P50 for Dashboard

### ISSUE THREAD

**Issue by arshkkk** [openstatusHQ/openstatus#431]
### Preliminary Checks

- [X] I have reviewed https://docs.openstatus.dev/ for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/openstatusHQ/openstatus/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to OpenStatus. Please ask questions in our Discord community: https://discord.com/invite/dHD4JtSfsn.

### Description

Would be insightful for to see Latencies for last 1 Day, 1 Week on dashboard and status page

**Comment by thibaultleouay** [comment]
@arshkkk  this a has been done 🔥
