### ISSUE TITLE
Fix hero grammar

### ISSUE THREAD

**Issue by dotarjun** [openstatusHQ/openstatus#47]
![image](https://github.com/mxkaske/openstatus/assets/71163609/fa6c1899-d415-4161-a2bd-9b77a88413a5)

"OpenStatus is an open source alternative to your current monitoring service with beautiful status page.
should be
OpenStatus is an open source alternative to your current monitoring service with **a** beautiful status page.

**Comment by thibaultleouay** [comment]
@dotarjun thanks a lot for your pr 🔥
Greatly appreciate it
