### ISSUE TITLE
UI: height of submit button doesnt match input field

### ISSUE THREAD

**Issue by dotarjun** [openstatusHQ/openstatus#49]
![image](https://github.com/mxkaske/openstatus/assets/71163609/c4bcd12c-c938-46f2-92da-a49e7dc2edf4)

i would like to be assigned to this

**Comment by thibaultleouay** [comment]
Hello @dotarjun, 
that would be fantastic,

**Comment by mxkaske** [comment]
Feel free to drop a PR! 🙌

I think I had that issue and it's due to "Password Managers" adding an extra "hidden" `div` next to the input field. 👀

**Comment by mxkaske** [comment]
@dotarjun the issue has been resolved by @nkilm. Feel free to let us know if you still have it.
