### ISSUE TITLE
Use BiomeJS instead of prettier 

### ISSUE THREAD

**Issue by thibaultleouay** [openstatusHQ/openstatus#492]
### Preliminary Checks

- [X] I have reviewed https://docs.openstatus.dev/ for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/openstatusHQ/openstatus/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to OpenStatus. Please ask questions in our Discord community: https://discord.com/invite/dHD4JtSfsn.

### Description

Switch from prettier to biomejs 

We should use the same config, also set up vscode with biomejs

**Comment by Ipriyankrajai** [comment]
Hey @thibaultleouay ,
Should I refer to [this](https://biomejs.dev/guides/big-projects/)? Or do you have another reference?
