### ISSUE TITLE
Allow markdown in incident reports

### ISSUE THREAD

**Issue by andig** [openstatusHQ/openstatus#507]
### Preliminary Checks

- [X] I have reviewed https://docs.openstatus.dev/ for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/openstatusHQ/openstatus/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to OpenStatus. Please ask questions in our Discord community: https://discord.com/invite/dHD4JtSfsn.

### Description

It would be nice if incident reports could use Markdown. My simple use case is adding a link to our Github Issue tracken, but general Markdown support would be nice.

**Comment by thibaultleouay** [comment]
https://github.com/openstatusHQ/openstatus/assets/13894054/f400fe18-e5a2-44a4-83a5-586b3aa77477

Hello @andig, 

Markdown is already supported 🔥

**Comment by andig** [comment]
Ahh, I see- it just doesn't linkify automatically. MD confirmed working, thank you!
