### ISSUE TITLE
Fix spelling mistake in README.md

### ISSUE THREAD

**Issue by nkilm** [openstatusHQ/openstatus#51]
Hey, I've noticed a minor spelling mistake in contact section of README.

![image](https://github.com/mxkaske/openstatus/assets/79012023/539228d6-bf9b-4916-8eb8-c1d593ecb793)

I've opened a PR which fixes this issue.

**Comment by thibaultleouay** [comment]
Thanks a lot @nkilm

**Comment by nkilm** [comment]
@thibaultleouay Happy to help!

**Comment by nkilm** [comment]
Fixed via #50
