### ISSUE TITLE
[🪲 Bug]: New Notification Channels Created with Empty Fields

### ISSUE THREAD

**Issue by ashrafchowdury** [openstatusHQ/openstatus#526]
### Preliminary Checks

- [X] I have reviewed the documentation: https://docs.openstatus.dev/
- [X] I have searched for existing issues: https://github.com/openstatusHQ/openstatus/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to OpenStatus. Please ask questions in our Discord community: https://www.openstatus.dev/discord

### Description

It is currently possible to create new notification channels without filling in any of the required fields. This leads to invalid channels that cannot be used to receive notifications.

**Steps to reproduce:**

1. Navigate to the "Notification Channels" page.
2. Add a `condition`  on the Confirm button to ensure that the input field isn't empty before submitting the new Notification.
3. Run an in-depth test to ensure every channel is working properly.

**Expected behaviour:**

The system should prevent the creation of a new notification channel with empty fields and display an error message.

**Actual behaviour:**

A new notification channel is created even though all fields are empty.

## Bug Preview

https://github.com/openstatusHQ/openstatus/assets/87828904/6bcaf9d4-921c-4c4a-a7d3-b8b4d704d4d5

### Environment

```Shell
System:
    OS: Windows 11 10.0.22621
    CPU: (8) x64 AMD Ryzen 5 3400G with Radeon Vega Graphics    
    Memory: 461.96 MB / 5.95 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.10.2 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (119.0.2151.97)
    Internet Explorer: 11.0.22621.1
```

**Comment by ashrafchowdury** [comment]
**I would like to work on this issue if all sounds good**

**Comment by ashrafchowdury** [comment]
Hey guys, do you have any updates on how to deal with this issue?

**Comment by mxkaske** [comment]
Hey @ashrafchowdury! 

No updates but I think to know how to easily fix the issue:

```ts
// notification-form.tsx
function onSubmit({ data }) {
  // ...
  if (data === "") {
    form.setError("data", { message: "This field is required" });
    return;
  }
}
```

It's because `data` is an empty string, and therefore valid and the form will not invalidate the input field.

If you are interested to, feel free to drop a PR.
