### ISSUE TITLE
[OPE-44] Allow user to choose theme for status page

### ISSUE THREAD

**Issue by thibaultleouay** [openstatusHQ/openstatus#53]
* [ ] check tremorlabs colors
* [ ] 

<sub>From [SyncLinear.com](https://synclinear.com) | [OPE-44](https://linear.app/openstatus/issue/OPE-44/allow-user-to-choose-theme-for-status-page)</sub>

**Comment by theprogrammerinyou** [comment]
Hi can you assign me to this?

**Comment by mxkaske** [comment]
We have the dark mode support which we could merge, wdyt @thibaultleouay?

**Comment by mxkaske** [comment]
I am taking care of merging it and support both, dark/light mode. Even though it is not the scope of this ticket, let's just do it and close the ticket and epic and start from 0 regarding "theme".
