### ISSUE TITLE
[📃 Docs]: The section for project installation requires an update.

### ISSUE THREAD

**Issue by ashrafchowdury** [openstatusHQ/openstatus#537]
### Type of documentation issue

Incorrect Information, Missing Information, Other

## Description

I'm having trouble setting up the project locally and I believe the issue lies with the installation guide provided in the documentation. It seems the references to the `libsql/sqld` repository are outdated, as the server has moved its location.

I'm using Windows 11, that's why I used WSL(Windows Subsystem For Linux) to set the database.

**Without setting up sqld, the project won't start locally.**

## Screenshots

![image](https://github.com/openstatusHQ/openstatus/assets/87828904/44f14f33-737b-4325-b19c-8cb777ca298c)

`libsql/sqld` repository

![image](https://github.com/openstatusHQ/openstatus/assets/87828904/93e89315-d54d-491a-bc99-017eb8018367)

## My system configuration

```
System:
    OS: Windows 11 10.0.22621
    CPU: (8) x64 AMD Ryzen 5 3400G with Radeon Vega Graphics    
    Memory: 461.96 MB / 5.95 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.10.2 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (119.0.2151.97)
    Internet Explorer: 11.0.22621.1
```

**Comment by skushagra9** [comment]
Hey , I was having the same problem , I switched to Linux and now there is no problem as such

**Comment by skushagra9** [comment]
But you can run this without setting up the database. Please check

**Comment by thibaultleouay** [comment]
@ashrafchowdury 

I'm currently rewriting the docs see #1096  
So i will close it
