### ISSUE TITLE
[docs] Incident automation

### ISSUE THREAD

**Issue by jd-apprentice** [openstatusHQ/openstatus#545]
### Type of documentation issue

Missing Information

### Describe the problem and the proposed solution

Hi! I was reading the documentation and one section caught my attention but is seems not complete at the moment

the [Incident automation](https://docs.openstatus.dev/incident-automation/get-started#how-to-define-an-incident-automation) seems to be under construction but just mentions about a yaml file, but where? is not clear at least for me.

**Comment by mxkaske** [comment]
Hey @jd-apprentice, it is still on our roadmap, but we haven't touched it yet.

**Comment by jd-apprentice** [comment]
> Hey @jd-apprentice, it is still on our roadmap, but we haven't touched it yet.

Hey! Thanks for the reply, I'll wait then!
