### ISSUE TITLE
[OPE-50] Settings page

### ISSUE THREAD

**Issue by thibaultleouay** [openstatusHQ/openstatus#55]
create a shell page for settings 

<sub>From [SyncLinear.com](https://synclinear.com) | [OPE-50](https://linear.app/openstatus/issue/OPE-50/settings-page)</sub>

**Comment by Harish-b-03** [comment]
Heyy @thibaultleouay @mxkaske  :wave:,

I would like to work on this issue. is this open for everyone to work? If yes, can you please guide me on how and where to get more information about this issue?

Thank you :grin:

**Comment by mxkaske** [comment]
Hey @Harish-b-03! Feel free to join [discord](https://discord.com/invite/dHD4JtSfsn)! Let's chat here. Cuz those issues under construction. Sorry about that.

**Comment by mxkaske** [comment]
Arrived with #178.
