### ISSUE TITLE
[OPE-51] Edit monitor

### ISSUE THREAD

**Issue by thibaultleouay** [openstatusHQ/openstatus#56]
We should be able to edit a monitor 

* [ ] Status → Pause/active  
* [ ] Name 
* [ ] Description

<sub>From [SyncLinear.com](https://synclinear.com) | [OPE-51](https://linear.app/openstatus/issue/OPE-51/edit-monitor)</sub>

**Comment by Harish-b-03** [comment]
Heyy @thibaultleouay :wave:,

I would like to work on this issue. is this open for everyone to work?

Thank you :grin:

**Comment by mxkaske** [comment]
Hey @Harish-b-03! 👋 Thanks for your interest. This is already in work and we can soon close it. 
Our bad, we haven't assigned us yet.

Feel free to check some other issues! 🚀
