### ISSUE TITLE
The Toast Notification is persistent. 

### ISSUE THREAD

**Issue by dibyansh01** [openstatusHQ/openstatus#573]
### Preliminary Checks

- [X] I have reviewed the documentation: https://docs.openstatus.dev/

- [X] I have searched for existing issues: https://github.com/openstatusHQ/openstatus/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to OpenStatus. Please ask questions in our Discord community: https://www.openstatus.dev/discord

### Description

**Steps to reproduce:**

1. Step 1 - Navigate to the OpenStatus 'Monitors' dashboard.
2. Step 2  - Create a new monitor. 

**Expected behavior:**

After successfully creating a monitor, the success toast message should automatically disappear for a better user experience. This behavior applies not only here but also to all other simple success or error messages, unless they contain a navigation link.

**Actual behavior:**

The toast message remains persistent and requires manual closing.

Here is the demo: 

[Screencast from 01-13-2024 05:39:40 PM.webm](https://github.com/openstatusHQ/openstatus/assets/129924389/305c20e3-82a3-4522-95fd-83a7d507ff32)

### Environment

```Shell
System:
    OS: Linux 6.5 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 1.95 GB / 7.63 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.17.1 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.6.7 - /usr/bin/npm
    pnpm: 8.12.1 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chrome: 120.0.6099.216
```

**Comment by mxkaske** [comment]
Thanks @dibyansh01! That's definitely something that annoys me as well - but for some reasons we haven't touched it until now. There is a PR up to replace it with Sonner that would fix the problem.
