### ISSUE TITLE
[OPE-53] Create ContentLayer Changelog

### ISSUE THREAD

**Issue by thibaultleouay** [openstatusHQ/openstatus#58]
<sub>From [SyncLinear.com](https://synclinear.com) | [OPE-53](https://linear.app/openstatus/issue/OPE-53/create-contentlayer-changelog)</sub>

**Comment by nkilm** [comment]
I can work on this as I've already add the blog part using contentlayer.

**Comment by mxkaske** [comment]
Hey @nkilm! Sure, it would be great 🔥!
