### ISSUE TITLE
[OPE-52] Create ContentLayer Blog

### ISSUE THREAD

**Issue by thibaultleouay** [openstatusHQ/openstatus#59]
<sub>From [SyncLinear.com](https://synclinear.com) | [OPE-52](https://linear.app/openstatus/issue/OPE-52/create-contentlayer-blog)</sub>

**Comment by nkilm** [comment]
Hey @thibaultleouay! I'd love to work on this feature. I've personally used [contentlayer](https://contentlayer.dev) for my [personal website](https://nikhilmohite.com/blog).

**Comment by thibaultleouay** [comment]
That would be awesome @nkilm

**Comment by nkilm** [comment]
@thibaultleouay I was having several doubts including setting up the 'dev' environment locally. Where can I contact you? I see that discord channel is not yet created.

**Comment by thibaultleouay** [comment]
@nkilm the discord is up 🚀

**Comment by nkilm** [comment]
> @nkilm the discord is up 🚀

Excellent!

**Comment by Ipriyankrajai** [comment]
> @nkilm the discord is up rocket

@thibaultleouay can you share me Discord link?

**Comment by mxkaske** [comment]
Sorry about that @Ipriyankrajai! Here the [link](https://discord.com/invite/dHD4JtSfsn). See you there! 🚀
