### ISSUE TITLE
Add Incidents 

### ISSUE THREAD

**Issue by thibaultleouay** [openstatusHQ/openstatus#599]
### Preliminary Checks

- [X] I have reviewed https://docs.openstatus.dev/ for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/openstatusHQ/openstatus/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to OpenStatus. Please ask questions in our Discord community: https://discord.com/invite/dHD4JtSfsn.

### Description

We should add a route for the Incident in the server

We should be able to fetch/create incident with our API server

**Comment by skushagra9** [comment]
Hey, can I work on this ??

**Comment by thibaultleouay** [comment]
@skushagra9  For sure, 
We should add some basic endpoint  `/openstatus/apps/server/src/v1` to allow to work with incident via the API 
We should also include some OpenAPI doc 
If you can add one test it's 🔥

**Comment by skushagra9** [comment]
oh yes, sure recently I have been learning about openapi

**Comment by skushagra9** [comment]
it is resolved ig ?

**Comment by thibaultleouay** [comment]
Resolved by #604
