### ISSUE TITLE
The API should return the proper error status code 

### ISSUE THREAD

**Issue by thibaultleouay** [openstatusHQ/openstatus#629]
### Description

ATM when an API call fail the server return a status 200 with the error,
It should return the correct error status code 

`    return c.jsonT({ code: 401, message: "Already subscribed" });
`
to  
`
    return c.jsonT({ code: 401, message: "Already subscribed" }, 401);
`

**Comment by skushagra9** [comment]
Hey, I am interested to work on this

**Comment by thibaultleouay** [comment]
Thanks you @skushagra9 🙏
