### ISSUE TITLE
Add status page endpoint for the API

### ISSUE THREAD

**Issue by thibaultleouay** [openstatusHQ/openstatus#631]
### Description

We should be able to create/update/get/delete status page via the API

**Comment by skushagra9** [comment]
I am interested to work on this issue

**Comment by iknlaxmi** [comment]
hi,please assign this to me if not assigned to anyone?

**Comment by Nabhag8848** [comment]
Hey @skushagra9 Wanna Collab on this or have any progress on GET Status Page ? +  I have been working around #33  and we need GET Status Page.

**Comment by skushagra9** [comment]
please proceed, with this

**Comment by Nabhag8848** [comment]
@skushagra9 Just little ambiguity, 
You mean i should take up whole issue or just GET one or You are no longer working on this issue ?

**Comment by skushagra9** [comment]
actually, I have some work in my company , so won't be able to work on it for now, 
If you want , you can take it up

**Comment by Nabhag8848** [comment]
> actually, I have some work in my company , so won't be able to work on it for now, If you want , you can take it up

Cool Thanks ! Working on it !
