### ISSUE TITLE
Remove clerk and use lucia

### ISSUE THREAD

**Issue by thibaultleouay** [openstatusHQ/openstatus#653]
### Description

We should remove clerk and use lucia instead

We should do the migration for our current user

It will improved the DX for new users without the need to rely on a external third party

**Comment by pilcrowonpaper** [comment]
A simple database structure would be using 3 db tables:

- User (required by Lucia)
- Session (required by Lucia)
- OAuth accounts

The OAuth account table would look something like this:

| field | type | description |
| - | - | - |
| id | any | |
| user_id | string | the user linked to the account |
| provider_id | string | `"github"` or `"google"` |
| provider_user_id | string | GitHub or Google user ID |

So from Clerk, you need to export the user data and all OAuth providers linked to each user.

For OAuth, we recommend using [Arctic](https://arctic.js.org) to handle the callback.

**Comment by pilcrowonpaper** [comment]
As for setting up Lucia, we have [a Drizzle adapter](https://lucia-auth.com/database/drizzle) and the docs have Next.js specific guides
