### ISSUE TITLE
Add RSS feed to changelogs

### ISSUE THREAD

**Issue by thomasbnt** [openstatusHQ/openstatus#656]
### Description

Following [changelogs](https://www.openstatus.dev/changelog) with an RSS feed.

**Comment by mxkaske** [comment]
Yes!

**Comment by thibaultleouay** [comment]
Fixed with #719  

the link is https://www.openstatus.dev/changelog/feed.xml

**Comment by thomasbnt** [comment]
Awesome! Thanks! 🥳🎉
