### ISSUE TITLE
[OPE-54] Improve DX for new developers

### ISSUE THREAD

**Issue by thibaultleouay** [openstatusHQ/openstatus#67]
We should improve DX for new development 

A single command should launched a local dev 

<sub>From [SyncLinear.com](https://synclinear.com) | [OPE-54](https://linear.app/openstatus/issue/OPE-54/improve-dx-for-new-developers)</sub>

**Comment by lazyfuhrer** [comment]
Hey I'd like to work on this. Assign me @thibaultleouay

**Comment by mxkaske** [comment]
Hey @lazyfuhrer, sorry for not being reactive. If you are still interested, feel free to drop a PR for it!

**Comment by AmoabaKelvin** [comment]
Hello @mxkaske
Do you think having some sought of makefile that runs a bunch of commands will do?

Like, starting up turso, running migrations, starting the apps(web and documentation), launching ngrok on the web port and then displaying the URL(which will be used for the webhook in clerk).

Let me know what you think.

**Comment by mxkaske** [comment]
That would be 🔥. Wdyt, @thibaultleouay?

**Comment by thibaultleouay** [comment]
Oh yes that could be super great

**Comment by timzolleis** [comment]
Hi guys, just wondering if there has been any progress on this?

I set up a local dev environment (and soon the prod too) with docker, since some people using windows might not be able to run it properly otherwise.

Would you be interested in that aswell?

Kind regards

**Comment by skushagra9** [comment]
I am interested to work upon this @thibaultleouay @mxkaske

**Comment by thibaultleouay** [comment]
@skushagra9 that would be super nice 👍
