### ISSUE TITLE
RSS feed for blog

### ISSUE THREAD

**Issue by tarasglek** [openstatusHQ/openstatus#718]
### Description

Hi, i would love to follow your blog, but there isn't an rss feed.

**Comment by thibaultleouay** [comment]
Fixed with #719

**Comment by thibaultleouay** [comment]
https://www.openstatus.dev/blog/feed.xml

**Comment by tarasglek** [comment]
Signed up for you service due to quality of blog, thanks for fixing this. Will eval free offering for now
