### ISSUE TITLE
User Timezone

### ISSUE THREAD

**Issue by ghost** [openstatusHQ/openstatus#733]
### Description

As a user i want to see my country timezone instead of UTC only

Solution: Timezone should be autocatically updated based on the user location
![image](https://github.com/openstatusHQ/openstatus/assets/148574520/00331149-4ea8-46dd-9795-89a5292afdee)

**Comment by mxkaske** [comment]
Hey @Mathyu-Serverly!

The aggregated data from the `Tracker` itself is in UTC. That is why the 'Status Check' date was set to UTC as well. We can change the 'Status Check' easily to the users timezone, but its much harder to aggregate data for each timezone on Tinybird (as it would require a materialized view for each timezone). We are in the discussion of adding a few mv's for bigger timezones like PST, EST, CET but it would open the discussion, why not adding more timezones and that could require us to support every single timezone.

An option would be to have the users timezone with a tooltip showing the UTC timezone. E.g:

![CleanShot 2024-04-06 at 12 58 21@2x](https://github.com/openstatusHQ/openstatus/assets/56969857/8a68f6a9-8f3a-42f3-a472-d9be9aa65411)
