### ISSUE TITLE
footer links take up full width (may or may not be intended)

### ISSUE THREAD

**Issue by ca-lee-b** [openstatusHQ/openstatus#780]
### Reproduction / Replay Link (Optional)

![gif](https://github.com/openstatusHQ/openstatus/assets/79728151/746dedd6-3f1e-496f-a754-30fa08e48232)

### Description

**Steps to reproduce:**

1. Scroll down to bottom of the marketing pages
2. Hover over the footer links

**Expected behavior:**
links dont take up full space

**Actual behavior:**
notice how the links are hovered even when the cursor is away from them

### Environment

Chrome on MacOS

**Comment by officialrajdeepsingh** [comment]
It error occurs due to width, and assign me to fix this issue.

**Comment by mxkaske** [comment]
It was intended, but I am not sure if it is a good pattern (maybe there is an a11y convension for it).

Feel free to provide a fix for it.
