### ISSUE TITLE
Noticed a small typo in the waitlist email

### ISSUE THREAD

**Issue by harshPPatel** [openstatusHQ/openstatus#79]
I noticed a small typo in the email I received after joining the waitlist. We are missing Y in the highlighted paragraph.

I know it's a small fix and I would have looked into repo, before creating this Issue, but I am on my phone and unable to do it properly.

Apologies, if I reported it in a wrong place 🙏.

![image](https://github.com/openstatusHQ/openstatus/assets/36562266/e1b17a28-dce5-48e7-b117-92a358f37faf)

**Comment by nkilm** [comment]
@harshPPatel Nice catch. I'll open a PR to fix this issue.

**Comment by mxkaske** [comment]
Thanks both! 🙌 

@harshPPatel, it's the right place!
