### ISSUE TITLE
Badge might not look sharp 

### ISSUE THREAD

**Issue by thibaultleouay** [openstatusHQ/openstatus#798]
### Description

![image](https://github.com/openstatusHQ/openstatus/assets/13894054/7a9444f4-0d19-4eac-bb3b-52e2bb5c31d8)

it looks a bit pixelated

**Comment by Sama-004** [comment]
![image](https://github.com/openstatusHQ/openstatus/assets/70210929/8b11c305-6d66-4b74-8282-4b142124dd70)


looks good to me @thibaultleouay

**Comment by thibaultleouay** [comment]
@Sama-004 on our page we are using the react widget 

The SVG is the one with issue

**Comment by Abbhiishek** [comment]
hey @thibaultleouay  would like to work on this.

**Comment by thibaultleouay** [comment]
@Abbhiishek  would love that 

It's in this file

https://github.com/openstatusHQ/openstatus/blob/7d3b31f1af50d92e82df87f3f6571e266119516a/apps/web/src/app/status-page/%5Bdomain%5D/badge/route.tsx#L12

maybe one size is wrong we should probably have multiple size as argument ?

**Comment by Abbhiishek** [comment]
hey @thibaultleouay 

locally cloning the repo fails due to invalid path.
I have attached logs below:

```
error: invalid path 'apps/docs/api-reference/incident/get-incident:id.mdx'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

Even when i tried checking out to main, the same thing happened.

```
> git checkout -q main
error: invalid path 'apps/docs/api-reference/incident/get-incident:id.mdx'
error: invalid path 'apps/docs/api-reference/incident/put-incident:id.mdx'
error: invalid path 'apps/docs/api-reference/monitor/delete-monitor:id.mdx'
error: invalid path 'apps/docs/api-reference/monitor/get-monitor:id.mdx'
error: invalid path 'apps/docs/api-reference/monitor/get-monitor:id/summary.mdx'
error: invalid path 'apps/docs/api-reference/monitor/put-monitor:id.mdx'
error: invalid path 'apps/docs/api-reference/notification/get-notification:id.mdx'
error: invalid path 'apps/docs/api-reference/page/get-page:id.mdx'
error: invalid path 'apps/docs/api-reference/page/post-page:id/update.mdx'
error: invalid path 'apps/docs/api-reference/page/put-page:id.mdx'
error: invalid path 'apps/docs/api-reference/status_report/delete-status_report:id.mdx'
error: invalid path 'apps/docs/api-reference/status_report/get-status_report:id.mdx'
error: invalid path 'apps/docs/api-reference/status_report/post-status_report:id/update.mdx'
error: invalid path 'apps/docs/api-reference/status_report_update/get-status_report_update:id.mdx'
```

**Comment by thibaultleouay** [comment]
@Abbhiishek  are you on windows?

**Comment by Abbhiishek** [comment]
> @Abbhiishek are you on windows?

yep :)

**Comment by thibaultleouay** [comment]
This has been fix you can specify a size for the badge 

`badge?size=sm` 
with the following variable 
- sm 
- md
- lg 
- xl
