### ISSUE TITLE
[docs] Improved contribution.md

### ISSUE THREAD

**Issue by jonnicholson94** [openstatusHQ/openstatus#834]
### Type of documentation issue

Missing Information

### Describe the problem and the proposed solution

Would like to contribute to OpenStatus - but the contribution guidelines are pretty minimal! I'd be happy to contribute and improve this and would be a good starter PR for me. Feel free to assign if you're happy for me to look at this for you!

**Comment by mxkaske** [comment]
I agree! If you are interested to work on it and learn OpenStatus that way, feel free to take it! It’s highly appreciated. 🫶

Also feel free to send a message on Discord if you get stuck somewhere.
