### ISSUE TITLE
[docs] Remove Trigger.dev from home page

### ISSUE THREAD

**Issue by Ipriyankrajai** [openstatusHQ/openstatus#838]
### Type of documentation issue

Incorrect Information

### Describe the problem and the proposed solution

status.trigger.dev is using https://betterstack.com/ to monitor status.

![image](https://github.com/openstatusHQ/openstatus/assets/32142351/d76ea1b6-a131-4e2e-92ca-0a3f852179eb)

**Comment by sidhuiwnl** [comment]
can i work on this issue?

**Comment by saitejainampudi** [comment]
How can I start working on this, what should be the final output

**Comment by thibaultleouay** [comment]
closed with #985
