### ISSUE TITLE
Cloning monitors

### ISSUE THREAD

**Issue by mxkaske** [openstatusHQ/openstatus#919]
### Description

We should be able to 'create' or 'clone' a monitor to take all the settings with us (e.g. timeout, assertions, status page relationship, monitor tag relationship,...)

Include a new Dropdown Item

![CleanShot 2024-07-08 at 20 38 48@2x](https://github.com/openstatusHQ/openstatus/assets/56969857/f0993123-d437-4648-b0dc-39c2f0bb50fb)

**Comment by Ipriyankrajai** [comment]
Hey @mxkaske ,
I would like to work on this.

**Comment by Ipriyankrajai** [comment]
Hello @mxkaske,

When the user clicks on the clone action, should I redirect them to the `/monitors/new` page and preload the values?

**Comment by mxkaske** [comment]
I like the idea but if we would like to preload the values _but not save the cloned monitor_ some issue we will face is:
- How to pass the`defaultValues` to `/monitors/new`: Via `localStorage`/`sessionStorage` but we will render on the client or via `searchParams` and we can render server-side
- Requires a change on `handleSubmit` of the form as we currently, we have:

```ts
    if (defaultValues) {
      await api.monitor.update.mutate(props);
    } else {
      await api.monitor.create.mutate(props);
    }
```

Probably, a simple `if (defaultValues.id) ...` could be it.

Otherwise, we could clone (+ maybe set `active: false` to avoid to test the endpoint immediately), save the monitor by default and redirect the user to `/monitors/[id]/edit` to be able to edit it right away.

What are your thoughts?

**Comment by Ipriyankrajai** [comment]
I prefer the second approach where we first create the monitor and then redirect the user to `/monitors/[id]/edit`.

**Comment by mxkaske** [comment]
Perfect! What we can do is deactivating the monitor `onClone` and add a `?active=true` search param to override the defaultValue to be set the `active` value back to `true`.

```ts
    <MonitorForm
      defaultValues={{
        ...monitor,
        active: searchParams.get("active") || monitor.active
      }}
      {...}
    />
```

you might need to use `zod` for validation.
