### ISSUE TITLE
Add pagination to changelog/blog main page

### ISSUE THREAD

**Issue by thibaultleouay** [openstatusHQ/openstatus#923]
### Description

When we are on the openstatus.dev/changelog or openstatus.dev/blog, we display all our content. We should add pagination to show only the last 10 entries.

**Comment by Skye967** [comment]
I submitted a pull request with the changes. Let me know what you guys think. :)

**Comment by Anonymous-hss** [comment]
Hello I want to work on this issue, could you please assign this issue to me. Thanks!

**Comment by mxkaske** [comment]
Hey @Anonymous-hss! @Skye967 already provided with a PR.

We'll keep an eye open for another good issue if you are interested to contribute!

**Comment by Anonymous-hss** [comment]
@mxkaske yes sure looking forward to contribute
