### ISSUE TITLE
feat: add `rehype-pretty-code` dark mode support

### ISSUE THREAD

**Issue by mxkaske** [openstatusHQ/openstatus#930]
### Description

Right now, the `pre` code block doesn't support dark mode. It would be great to have a dark theme.

Documentation: https://rehype-pretty.pages.dev/#multiple-themes-dark-and-light-mode

Open for theme suggestions.

![CleanShot 2024-07-12 at 22 20 06@2x](https://github.com/user-attachments/assets/6ad53b07-5e74-4149-b352-0df7b092bf2a)
![CleanShot 2024-07-12 at 22 19 44@2x](https://github.com/user-attachments/assets/8c502f21-7eee-4cb0-ae19-9c5d6cfa3fd8)

**Comment by PrateekPsingh** [comment]
Hello I want to work on this issue, could you please assign this issue to me. Thanks!

**Comment by Sahilpingale** [comment]
> Hello I want to work on this issue, could you please assign this issue to me. Thanks!

I tried to work on this one and looks like there might be an issue with rehype-pretty-code as it is rendering code blocks twice when using multiple themes. 

Reference https://github.com/rehype-pretty/rehype-pretty-code/issues/107

**Comment by Trjindal** [comment]
hi @mxkaske the rehype pretty , say that the config file should be of .mjs instead .js extension. So do i change the config file for the  same or should we switch to some other package ?? 
![image](https://github.com/user-attachments/assets/810dbf34-2c6d-4502-8050-31d325b4959e)

**Comment by mxkaske** [comment]
Hey guys! Amazing for your interest!

Ideally we stick with `shiki` and `rehype-pretty-code`. Feel free to bump or change file extension name if it helps.

Feel free to share more issues you face.

**Comment by manaskumar3003** [comment]
Hey , is it already assigned or may i work on this??

**Comment by mxkaske** [comment]
This is not assigned to anyone.

**Comment by R0hitG0yal** [comment]
Hi @mxkaske I want to work on this issue, can you please assign this issue to me. Thanks!

**Comment by amardeep911** [comment]
Hey, I would like to work on this. Is this already fixed?

**Comment by mxkaske** [comment]
Hey guys, please simply create a PR and attach that issue.

**Comment by Ratnadeep2k** [comment]
> Hey guys, please simply create a PR and attach that issue.

can you please elaborate the issue ?

**Comment by mxkaske** [comment]
Hey @Ratnadeep2k! My bad. I was referring to this issue, #930. 

The best would be to start with a PR that has a first draft of how to possibly solve dark mode support for the code sections.

I haven't assigned anyone because of the amount of helpful hands. I'd be happy to exchange on a PR! Of course, if something is unclear, this thread would be the best.

Cheers!

**Comment by Trjindal** [comment]
Hey @mxkaske , i have tried to work on this issue . but there is some issue with rehype-pretty-code and shiki that when dual theme is applied on code blocks it renders twice. 
for reference you can see this https://github.com/rehype-pretty/rehype-pretty-code/issues/107

**Comment by Sama-004** [comment]
> Hey @mxkaske , i have tried to work on this issue . but there is some issue with rehype-pretty-code and shiki that when dual theme is applied on code blocks it renders twice. for reference you can see this [rehype-pretty/rehype-pretty-code#107](https://github.com/rehype-pretty/rehype-pretty-code/issues/107)

yeah I am also facing the same issue of duplicate codeblocks(one in light and one in dark) when adding dark theme to rehype

**Comment by mxkaske** [comment]
Gotcha! Do you have a reproducible PR for that where I can test it? Otherwise, will check try it out!

**Comment by mxkaske** [comment]
Solution: use tailwind to display or hide the blocks based on the `data-theme`. See #973 for the implementation.
