### ISSUE TITLE
post-deleting a monitor a UI exception is thrown

### ISSUE THREAD

**Issue by SeanCassiere** [openstatusHQ/openstatus#944]
### Description

**Steps to reproduce:**

1. Create a monitor.
2. Click on the monitor.
3. Navigate to "Setting" from the sidebar.
4. Select the tab labelled as "Danger".
5. Click on the button labelled as "Delete" and confirm the action in the dialog that pops up.
6. Observe the deletion go through and then the exception be thrown.

**Expected behavior:**

It should probably redirect you to the monitors list page or whatever post-deletion flow was intended here.

**Actual behavior:**

An exception is thrown on and displays the Next error screen.

<img width="877" alt="image" src="https://github.com/user-attachments/assets/e37b804a-bf3f-40fc-834e-da075606ce06">

I'd record a video, but after the deletion, I found out that the number of allowed monitors on the Hobby Plan has been reduced, and I don't want to remove the remaining ones that I have.

**Comment by SeanCassiere** [comment]
Console dump: [www.openstatus.dev-1721559244679.log](https://github.com/user-attachments/files/16323952/www.openstatus.dev-1721559244679.log)

PS: I do have Adblock enabled.

**Comment by mxkaske** [comment]
Thanks for sharing. Will check.

**Comment by mxkaske** [comment]
Fixed! We usually delete from the tables and then only need to do a `router.refresh`. In this case, we where trying to fetch an entry that doesn't exists.

We might wanna rework the error handling on app side to provide more valuable messages to the user.
