### ISSUE TITLE
Styling issue with copy to clipboard button on single code lines [CSS]

### ISSUE THREAD

**Issue by mxkaske** [openstatusHQ/openstatus#947]
### Description

The copy button looks fine when the code block has multiple lines. If single line, it looks off.

Possible solution, reduce the `top-` value to fit within a single line.

Very first changelog on `/changelog` page:
![CleanShot 2024-07-21 at 18 40 12@2x](https://github.com/user-attachments/assets/9f88570e-934d-4340-9d0b-f0e516b8cf13)

Section on `/features/monitoring` page:
![CleanShot 2024-07-21 at 18 42 11@2x](https://github.com/user-attachments/assets/7db591b1-7f43-48ae-a89f-dd85c7267536)

**Comment by arijitdn** [comment]
I will work on this

**Comment by amardeep911** [comment]
Hey, I like to work on this issue.

**Comment by krishnashah122** [comment]
Is anyone working on it?
If not, can I work on it?

**Comment by arijitdn** [comment]
> Is anyone working on it? If not, can I work on it?

I am working

**Comment by mxkaske** [comment]
Hey guys! Feel free to create a PR and attach the issue so we know its in progress!
