### ISSUE TITLE
Status Code assertion field isn't logical 

### ISSUE THREAD

**Issue by Mahmoudgalalz** [openstatusHQ/openstatus#988]
### Description

![image](https://github.com/user-attachments/assets/866bfa64-15d2-4af7-8396-a12c21688961)

1. it should be limited to 599

**Comment by nolostra** [comment]
can you please assign this to me ?

**Comment by mxkaske** [comment]
I've assigned you, @nolostra! Feel free to push a fix.

As a solution, I'd add a `min={100}` and `max={599}` integer to the input field. What do you think of it?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
